const { dismissModal } = require('./modal');
const {test,expect}=require('@playwright/test');const fs=require('node:fs');const path=require('node:path');
const {start,shot,panel,close,picker,entries,inspectPickers}=require('./qa-domains-ui');
const reports=[];test.afterAll(()=>{const file=path.resolve('test-results/page-audit/domains-coverage.json');fs.mkdirSync(path.dirname(file),{recursive:true});const saved=fs.existsSync(file)?file:'/tmp/qa-domains-evidence/domains-coverage.json';const old=fs.existsSync(saved)?JSON.parse(fs.readFileSync(saved,'utf8')).pages:[];const keys=new Set(reports.map(r=>r.route+'|'+r.variants.join(',')));fs.writeFileSync(file,JSON.stringify({pages:[...old.filter(r=>!keys.has(r.route+'|'+r.variants.join(','))),...reports]},null,2));fs.copyFileSync(file,'/tmp/qa-domains-evidence/domains-coverage.json')});
const csv='交易号,商户订单号,交易创建时间,付款时间,最近修改时间,交易来源地,交易类型,交易对方,商品名称,金额（元）,收/支,交易状态,服务费（元）,成功退款（元）,备注,资金状态\nfixture1,fixtureM,2026-10-01 01:00:00,2026-10-01 01:00:00,,PC,餐饮,商店,商品,99,支出,交易成功,0,72.6,fixture,已支付';
for(const [route] of entries)for(const [width,theme] of [[390,'light'],[390,'dark'],[768,'light'],[768,'dark'],[1440,'light'],[1440,'dark']])test(`逐页真实点击 ${route} ${width} ${theme}`,async({page})=>{
 test.setTimeout(60000);await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});const variant=width+'-'+theme,evidence=[],checks=['登录→生活目录入口点击','横向溢出','浏览器异常'],issues=[];const errors=[];page.on('pageerror',e=>errors.push(e.message));const state=await start(page,route);evidence.push(await shot(page,route,variant,'page'));
 try{
 await inspectPickers(page,page.locator('.mobile-page').last(),route,variant,evidence);checks.push('页面选择器逐一打开取消');
 if(route==='finance/index'){await picker(page,'年份','2026');checks.push('年份选择器');evidence.push(await shot(page,route,variant,'year'));}
 if(['finance/income','finance/expense'].includes(route)){
 const kind=route.endsWith('income')?'收入':'支出';
 await page.getByRole('button',{name:'新增',exact:true}).click();await panel(page,route,variant,'编辑'+kind,evidence);await close(page);
 await page.getByRole('button',{name:new RegExp('^编辑'+kind+'：')}).click();await panel(page,route,variant,'编辑'+kind,evidence);
 await page.getByRole('button',{name:'删除'+kind,exact:true}).click();evidence.push(await shot(page,route,variant,'delete-confirm'));await page.getByRole('dialog',{name:'删除'+kind,exact:true}).getByRole('button',{name:'取消',exact:true}).click();await close(page);
 await page.getByRole('button',{name:'统计',exact:true}).click();evidence.push(await shot(page,route,variant,'statistics'));checks.push('新增/编辑弹窗顶部底部/遮罩取消','编辑内删除确认/取消','统计展开');
 }
 if(route==='finance/import'){
 await page.getByRole('button',{name:'粘贴 CSV 内容',exact:true}).click();await page.locator('[aria-label="支付宝 CSV 内容"] textarea').fill(csv);await page.locator('[role=button][aria-label="解析预览"]').click();await expect(page.getByText('1 笔 · ¥26.40',{exact:true})).toBeVisible();await page.locator('[role=button][aria-label="编辑"]').click();await panel(page,route,variant,'导入记录',evidence);await page.locator('[role=dialog]').locator('[role=button][aria-label="保存预览"]').click();state.fail=true;await page.locator('[role=button][aria-label="确认导入"]').click();await expect(page.getByText('交易号已存在: fixture1',{exact:true})).toBeVisible();evidence.push(await shot(page,route,variant,'import-error'));checks.push('CSV解析/退款26.40','预览编辑保存','导入失败保留');
 }
 if(route==='finance/cards'){
 for(const action of ['新增银行卡','编辑']){if(action==='编辑'){await page.getByRole('button', { name: '银行卡更多操作', exact: true }).first().click();await page.getByRole('menuitem', { name: '编辑银行卡', exact: true }).click();}else await page.locator('[role=button][aria-label="'+action+'"]').first().click();await panel(page,route,variant,'银行卡',evidence);await page.getByRole('dialog',{name:'银行卡',exact:true}).getByRole('button',{name:'取消',exact:true}).click();}
 for(const action of ['新增标签','编辑标签']){await page.locator('[role=button][aria-label="'+action+'"]').first().click();await panel(page,route,variant,'标签',evidence);await page.locator('.modal-mask').last().click({position:{x:2,y:2}});}
 for(const action of ['删除银行卡','删除标签']){if(action==='删除银行卡'){await page.getByRole('button',{name:'银行卡更多操作'}).first().click();await page.getByRole('menuitem',{name:action,exact:true}).click();}else await page.locator('[role=button][aria-label="'+action+'"]').click();evidence.push(await shot(page,route,variant,action));await page.locator('[role=button][aria-label="取消"]').click();}
 await page.getByRole('button',{name:'银行卡更多操作'}).first().click();await page.getByRole('menuitem',{name:'查看卡号',exact:true}).click();await expect(page.getByText('6222 0000 1234',{exact:true})).toBeVisible();await page.getByRole('dialog',{name:'银行卡卡号',exact:true}).getByRole('button',{name:'关闭',exact:true}).click();checks.push('银行卡新增编辑长弹窗内部滚动','标签新增编辑弹窗','卡与标签删除确认取消','完整卡号显示');}
 if(route.startsWith('coding/')){await page.locator('[role=button][aria-label="账号绑定"]').click();await expect(page).toHaveURL(/profile\/bindings/);checks.push('账号绑定入口点击');evidence.push(await shot(page,route,variant,'bindings-destination'));}
 if(route==='relationship/index'){
 await page.locator('[role=button][aria-label="放大图谱"]').click();await page.locator('[role=button][aria-label="缩小图谱"]').click();await page.locator('[role=button][aria-label="复位图谱"]').click();
 await page.locator('[role=button][aria-label="新增人物"]').click();await panel(page,route,variant,'人物',evidence);await close(page);
 await page.locator('[role=button][aria-label="模拟人物"]').first().click();await panel(page,route,variant,'模拟人物',evidence);
 await page.locator('[role=button][aria-label="编辑人物"]').click();await panel(page,route,variant,'人物',evidence);await close(page);
 await page.locator('[role=button][aria-label="新增关系"]').click();await panel(page,route,variant,'关系',evidence);await close(page);
 await page.locator('[role=button][aria-label="编辑关系"]').click();await panel(page,route,variant,'关系',evidence);await close(page);await page.locator('[role=button][aria-label="删除关系"]').click();evidence.push(await shot(page,route,variant,'delete-relation'));await page.locator('[role=button][aria-label="取消"]').click();await page.locator('[role=button][aria-label="删除人物和关联关系"]').click();evidence.push(await shot(page,route,variant,'delete-confirm'));await page.locator('[role=button][aria-label="取消"]').click();await close(page);checks.push('图谱缩放复位','人物新增/详情/编辑长弹窗','关系新增弹窗','人物删除确认取消');}
 if(route==='messages/index'){
 await page.getByRole('button',{name:'全部已读',exact:true}).click();evidence.push(await shot(page,route,variant,'read-all-confirm'));await page.getByRole('button',{name:'取消',exact:true}).click();
 await page.getByRole('button',{name:'发送消息',exact:true}).click();await panel(page,route,variant,'发送消息',evidence);await close(page);
 await page.locator('.conversation').first().click();await expect(page.locator('.chat-input')).toBeVisible();evidence.push(await shot(page,route,variant,'chat'));
 await page.getByRole('button',{name:'消息操作',exact:true}).first().click();await page.getByRole('button',{name:'删除消息',exact:true}).click();evidence.push(await shot(page,route,variant,'delete-confirm'));await page.getByRole('button',{name:'取消',exact:true}).click();
 await page.getByRole('button',{name:'删除当前会话',exact:true}).click();evidence.push(await shot(page,route,variant,'conversation-delete-confirm'));await page.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('button',{name:'返回',exact:true}).click();
 await page.getByRole('button',{name:'管理消息',exact:true}).click();await page.getByRole('button',{name:'发送通知',exact:true}).click();await panel(page,route,variant,'发送消息',evidence);await close(page);await page.getByRole('button',{name:'管理员删除',exact:true}).click();evidence.push(await shot(page,route,variant,'admin-delete-confirm'));await page.getByRole('button',{name:'取消',exact:true}).click();
 await expect(page.getByRole('tab',{name:'AI',exact:true})).toHaveCount(0);checks.push('会话列表和聊天气泡','新消息/管理发送弹窗','消息与会话删除确认取消','AI入口已移除');}

 if(route==='mcp/index'){await page.locator('[role=button][aria-label="输入参数并调用 fixture_tool"]').click();await panel(page,route,variant,'fixture_tool',evidence);await page.locator('[aria-label="name"] input').fill('fixture');state.fail=true;await page.locator('[role=button][aria-label="执行工具"]').click();await expect(page.getByText('模拟工具失败',{exact:true})).toBeVisible();state.fail=false;await page.locator('[role=button][aria-label="执行工具"]').click();await expect(page.getByText('模拟执行成功',{exact:true})).toBeVisible();evidence.push(await shot(page,route,variant,'result'));await close(page);checks.push('工具弹窗/执行失败保留/重试成功');}
 if(route==='vault/index'){await page.locator('[role=button][aria-label="解锁"]').click();const unlock=await panel(page,route,variant,'解锁密码库',evidence);await unlock.locator('[aria-label="主密码"] input').fill('qa-master');await unlock.locator('[aria-label="确认主密码"] input').fill('qa-master');await unlock.locator('[role=button][aria-label="解锁"]').click();await expect(unlock).toHaveCount(0);await page.locator('[role=button][aria-label="新增密码"]').click();await panel(page,route,variant,'密码记录',evidence);await page.locator('[role=button][aria-label="密码生成器"]').click();await page.locator('[role=button][aria-label="生成密码"]').click();await expect(page.locator('[role=dialog]').locator('[aria-label="密码"] input')).not.toHaveValue('');evidence.push(await shot(page,route,variant,'generator'));await close(page);await page.locator('[role=button][aria-label="锁定"]').click();checks.push('首次解锁/确认主密码','新增密码長弹窗/生成器','锁定');}
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
 }catch(e){issues.push(e.message);throw e;}finally{reports.push({route,variants:[variant],checks,evidence,status:issues.length?'failed':'passed',issues})}
});

for(const width of [390,768])for(const theme of ['light','dark'])test(`密码库已有记录逐弹窗与失败保留 ${width} ${theme}`,async({page})=>{await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});const state=await start(page,'vault/index',{existingVault:true}),evidence=[],variant=width+'-'+theme+'-existing';await page.locator('[aria-label="解锁"][role=button]').click();const unlock=await panel(page,'vault/index',variant,'解锁密码库',evidence);await unlock.locator('[aria-label="主密码"] input').fill('qa-master');await unlock.locator('[aria-label="解锁"][role=button]').click();await expect(page.getByText('fixture-user',{exact:true})).toBeVisible();await page.locator('[aria-label="显示或隐藏密码"][role=button]').click();await expect(page.getByText('fixture-secret',{exact:true})).toBeVisible();await page.locator('[aria-label="编辑密码"][role=button]').click();const form=await panel(page,'vault/index',variant,'密码记录',evidence);await form.locator('[aria-label="密码"] input').fill('changed-fixture');state.fail=true;await form.locator('[aria-label="保存"][role=button]').click();await expect(form.getByText('模拟保存失败',{exact:true})).toBeVisible();await expect(form.locator('[aria-label="密码"] input')).toHaveValue('changed-fixture');evidence.push(await shot(page,'vault/index',variant,'save-error'));state.fail=false;await form.locator('[aria-label="保存"][role=button]').click();await expect(form).toHaveCount(0);expect(JSON.stringify(state.calls.at(-1))).not.toContain('changed-fixture');await page.locator('[aria-label="删除密码"][role=button]').click();evidence.push(await shot(page,'vault/index',variant,'delete-confirm'));await page.locator('[aria-label="取消"][role=button]').click();await page.locator('[aria-label="返回"][role=button]').click();await page.locator('[role=button][aria-label="密码库"]').last().click();await expect(page.locator('[aria-label="解锁"][role=button]')).toBeVisible();await expect(page.getByText('fixture-user',{exact:true})).toHaveCount(0);reports.push({route:'vault/index',variants:[variant],checks:['已有记录解锁/显示','编辑弹窗内部滚动/失败保留/密文成功保存','删除确认取消','返回目录再进入自动锁定敏感数据清理'],evidence,status:'passed',issues:[]})});
for(const file of ['alipay.csv','alipay.zip','wechat.xlsx'])test(`账单完整本地文件选择 ${file}`,async({page})=>{await page.setViewportSize({width:390,height:900});await start(page,'finance/import');const chooser=page.waitForEvent('filechooser');await page.locator('[role=button][aria-label="选择文件"]').click();await(await chooser).setFiles(path.resolve('tests/e2e/qa-domains-fixtures',file));await expect(page.getByText('1 笔 · ¥26.40',{exact:true})).toBeVisible();const evidence=[await shot(page,'finance/import','390-light-file',file+'-preview')];await page.locator('[aria-label="编辑"][role=button]').click();const modal=await panel(page,'finance/import','390-light-file-'+file,'导入记录',evidence);await expect(modal.locator('[aria-label="记账金额"] input')).toHaveValue('26.4');await expect(modal.locator('[aria-label="交易金额"] input')).toHaveValue('99');await close(page);reports.push({route:'finance/import',variants:['390-light-file-'+file],checks:['实际文件选择器导入完整本地fixture','支付宝CSV/ZIP或微信xlsx解析退款26.40','预览编辑交易原金额99与记账金额26.4保留'],evidence,status:'passed',issues:[]})});
test('消息离页清理新消息草稿',async({page})=>{await page.setViewportSize({width:390,height:900});await start(page,'messages/index');await page.getByRole('button',{name:'发送消息',exact:true}).click();await page.locator('[role=dialog] [aria-label="内容"] textarea').fill('mock-sensitive-content');await close(page);await page.getByRole('button',{name:'返回',exact:true}).click();await page.getByRole('button',{name:'消息中心',exact:true}).click();await page.getByRole('button',{name:'发送消息',exact:true}).click();await expect(page.locator('[role=dialog] [aria-label="内容"] textarea')).toHaveValue('');await expect(page.getByRole('tab',{name:'AI',exact:true})).toHaveCount(0);});

for(const [route] of entries)test(`逐页下拉失败重试和空态 ${route}`,async({page})=>{test.setTimeout(60000);await page.setViewportSize({width:390,height:900});const consoleErrors=[];page.on('console',msg=>{if(msg.type()==='error')consoleErrors.push(msg.text())});const state=await start(page,route),evidence=[];state.readFail=true;await require('./gestures').pullDown(page,'.mobile-page-scroll');await expect(page.getByText('QA 模拟加载失败',{exact:false}).first()).toBeVisible();evidence.push(await shot(page,route,'390-light-recovery','read-error'));state.readFail=false;await page.locator('[role=button][aria-label="重试"]').last().click();await expect(page.getByText('QA 模拟加载失败',{exact:false})).toHaveCount(0);await page.waitForLoadState('networkidle');evidence.push(await shot(page,route,'390-light-recovery','retried'));state.empty=true;await require('./gestures').pullDown(page,'.mobile-page-scroll');await page.waitForLoadState('networkidle');evidence.push(await shot(page,route,'390-light-recovery','empty'));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(consoleErrors).toEqual([]);reports.push({route,variants:['390-light-recovery'],checks:['真实下拉触摸事件加载失败可见','UI重试成功','模拟空结果显示/未绑定语义（编程页）'],evidence,status:'passed',issues:[]})});

test('桌面选择器快速取消关闭与立即重开无生命周期异常',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:768,height:900});await start(page,'finance/income');const evidence=[];await page.locator('[role=button][aria-label="新增"]').click();const modal=page.locator('[role=dialog][aria-label="编辑收入"]');const field=modal.locator('uni-picker[aria-label="类型"]');await field.click();await page.locator('.uni-picker-select .uni-picker-item:visible').first().waitFor();await page.locator('.uni-picker-mask:visible').last().click({position:{x:5,y:5}});await dismissModal(page);await page.waitForTimeout(350);expect(errors).toEqual([]);await page.locator('[role=button][aria-label="新增"]').click();const next=page.locator('[role=dialog][aria-label="编辑收入"] uni-picker[aria-label="类型"]');await next.click();await page.locator('.uni-picker-select .uni-picker-item:visible').first().waitFor();await page.locator('.uni-picker-mask:visible').last().click({position:{x:5,y:5}});await next.click();await page.waitForTimeout(350);await expect(page.locator('.uni-picker-select .uni-picker-item:visible').first()).toBeVisible();evidence.push(await shot(page,'finance/income','768-light-rapid','reopened-selector'));expect(errors).toEqual([]);reports.push({route:'finance/income',variants:['768-light-rapid'],checks:['取消选择器后立即关闭modal无null.remove','取消后立即重开选择器不被旧回调移走'],evidence,status:'passed',issues:[]})});
