const { dismissModal } = require('./modal');
const {test,expect}=require('@playwright/test');const fs=require('node:fs');const {setup,admin}=require('./qa-platform-fixtures');
const out='test-results/page-audit/platform';fs.mkdirSync(out,{recursive:true});fs.mkdirSync('/tmp/qa-platform-evidence',{recursive:true});
async function shot(page,name){await page.waitForTimeout(300);fs.mkdirSync(out,{recursive:true});await page.screenshot({path:`${out}/${name}.png`,fullPage:true});fs.copyFileSync(`${out}/${name}.png`,`/tmp/qa-platform-evidence/${name}.png`);const geom=await page.locator('.navigation-button,.icon-button,.dashboard-action,.life-action,.task-check,.delete-button,.category-option').evaluateAll(nodes=>nodes.map(n=>{const b=n.getBoundingClientRect(),child=n.querySelector('svg,img,.category-icon,.navigation-back-surface,.action-content,.delete-icon');const c=child?.getBoundingClientRect();return{class:n.className,label:n.getAttribute('aria-label'),width:b.width,height:b.height,display:getComputedStyle(n).display,dx:c?c.x+c.width/2-b.x-b.width/2:null,dy:c?c.y+c.height/2-b.y-b.height/2:null}}));fs.writeFileSync(`${out}/${name}-geometry.json`,JSON.stringify(geom,null,2));fs.writeFileSync(`/tmp/qa-platform-evidence/${name}-geometry.json`,JSON.stringify(geom,null,2));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const modal=page.getByRole('dialog').last();if(await modal.count()){const b=await modal.boundingBox();if(b&&b.height>650){await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.wheel(0,1800);await page.waitForTimeout(100);await page.screenshot({path:`${out}/${name}-bottom.png`,fullPage:true});fs.copyFileSync(`${out}/${name}-bottom.png`,`/tmp/qa-platform-evidence/${name}-bottom.png`);}}}
async function click(page,name){
 if (['dict-data','dict-types'].some(kind => page.url().includes('kind=' + kind)) && ['编辑','删除'].includes(name) && await page.getByRole('dialog').count() === 0) {
  await page.getByRole('button',{name:/更多操作$/}).first().click();
 }
 if (page.url().includes('/pages/profile/index') && ['账号绑定','修改密码','菜单锁'].includes(name)) {
  await page.getByRole('button',{name:'账号与安全',exact:true}).click();
 }
 await page.getByRole('button',{name:name,exact:true}).last().click();
}
async function back(page){
 const previous = page.url();
 await page.getByRole('button',{name:'返回',exact:true}).first().click();
 await expect(page).not.toHaveURL(previous);
 if (page.url().includes('/pages/profile/account-security')) {
  await page.getByRole('button',{name:'返回',exact:true}).first().click();
 }
}
for(const width of [390,768,1440])for(const theme of ['light','dark'])test(`真实菜单点击：我的各设置和弹窗 ${width} ${theme}`,async({page})=>{
await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});const errors=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);await shot(page,`${width}-${theme}-home`);await page.locator('uni-tabbar').getByText('我',{exact:true}).click();await shot(page,`${width}-${theme}-profile`);
for(const [entry,action] of [['基本设置',null],['账号绑定','新增绑定'],['修改密码','修改密码'],['菜单显示','恢复默认菜单'],['菜单锁','修改二级密码'],['API Key','新增'],['通知设置','配置飞书'],['系统设置','清除缓存'],['MBTI 测试',null],['CBTI 测试','开始测试'],['关于',null]]){
await click(page,entry);await page.waitForTimeout(250);await shot(page,`${width}-${theme}-${entry}-page`);if(action){await click(page,action);await page.waitForTimeout(150);await shot(page,`${width}-${theme}-${entry}-dialog`);const panel=page.getByRole('dialog');if(await panel.count()){const box=await panel.last().boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.y).toBeGreaterThanOrEqual(0);expect(box.y+box.height).toBeLessThanOrEqual(901);await dismissModal(page);}else if(await page.getByRole('button',{name:'取消',exact:true}).count())await click(page,'取消');}
await back(page);
}
await click(page,'退出登录');await shot(page,`${width}-${theme}-logout-confirm`);await click(page,'取消');expect(errors).toEqual([]);
});
for(const width of [390,768,1440])for(const theme of ['light','dark'])test(`真实管理目录逐kind点击 ${width} ${theme}`,async({page})=>{
await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});await setup(page);await page.locator('uni-tabbar').getByText('我',{exact:true}).click();await click(page,'管理与配置');await shot(page,`${width}-${theme}-admin-directory`);
for(const [kind,path,title] of admin){await click(page,title);await page.waitForTimeout(200);await shot(page,`${width}-${theme}-admin-${kind}`);if(!['config','feedback','operation','access'].includes(kind)){await click(page,'新增');await shot(page,`${width}-${theme}-admin-${kind}-new`);const modal=page.getByRole('dialog');await expect(modal).toBeVisible();await modal.getByRole('button',{name:'保存',exact:true}).click();await expect(modal.getByRole('alert')).toBeVisible();await dismissModal(page);}await back(page);}
});
for(const width of [390,768,1440])for(const theme of ['light','dark'])test(`生活分类与时迹入口弹窗 ${width} ${theme}`,async({page})=>{
await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});await setup(page);
await click(page,'新增时迹');await page.getByRole('dialog').waitFor();await shot(page,`${width}-${theme}-home-time-new`);await dismissModal(page);
await page.locator('uni-tabbar').getByText('时迹',{exact:true}).click();await shot(page,`${width}-${theme}-time-page`);await click(page,'筛选分类');await shot(page,`${width}-${theme}-time-filter`);await dismissModal(page);await click(page,'新增时迹');await shot(page,`${width}-${theme}-time-new`);await dismissModal(page);
await page.locator('uni-tabbar').getByText('全部',{exact:true}).click();await shot(page,`${width}-${theme}-life`);await page.locator('uni-tabbar').getByText('首页',{exact:true}).click();await click(page,'管理快捷导航');await shot(page,`${width}-${theme}-life-edit`);await click(page,'取消编辑');
for(const entry of ['个人分类','时间看板']){await click(page,entry);await page.waitForTimeout(200);await shot(page,`${width}-${theme}-${entry}`);if(entry!=='时间看板'){await click(page,'编辑分类');await shot(page,`${width}-${theme}-${entry}-edit`);await dismissModal(page);}await back(page);}
});
for(const width of [390,768,1440])for(const theme of ['light','dark'])test(`登录真实点击注册重置政策弹窗 ${width} ${theme}`,async({page})=>{
await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});await setup(page);await page.locator('uni-tabbar').getByText('我',{exact:true}).click();await click(page,'退出登录');await click(page,'退出');await shot(page,`${width}-${theme}-login`);
for(const entry of ['注册账号','忘记密码']){await click(page,entry);await shot(page,`${width}-${theme}-auth-${entry}`);await page.getByRole('textbox',{name:'邮箱',exact:true}).fill('fixture@example.test');await click(page,'发送验证码');await shot(page,`${width}-${theme}-auth-${entry}-sent`);await back(page);}
});
for(const width of [390,768,1440])for(const theme of ['light','dark'])test(`人格测试真实点击外部问卷和管理 ${width} ${theme}`,async({page})=>{
await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});await setup(page);await page.locator('uni-tabbar').getByText('我',{exact:true}).click();await click(page,'MBTI 测试');await click(page,'开始测试');await expect(page).toHaveURL(/personality\/external/);await shot(page,`${width}-${theme}-mbti-external`);await back(page);await shot(page,`${width}-${theme}-mbti-pending`);await back(page);await click(page,'CBTI 测试');await click(page,'人格管理');await shot(page,`${width}-${theme}-cbti-admin`);await click(page,'新增人格');await shot(page,`${width}-${theme}-cbti-admin-new`);await click(page,'保存人格');await shot(page,`${width}-${theme}-cbti-admin-invalid`);await dismissModal(page);await dismissModal(page);
});
for(const width of [390,768,1440])for(const theme of ['light','dark'])test(`有数据行编辑删除详情真实点击 ${width} ${theme}`,async({page})=>{
await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});const state=await setup(page,true);await page.locator('uni-tabbar').getByText('我',{exact:true}).click();
for(const [entry,edit,del] of [['账号绑定','编辑GitHub绑定','解除GitHub绑定'],['API Key',null,'删除'],['MBTI 测试','历史详情','删除测试记录']]){await click(page,entry);if(edit){await click(page,edit);await shot(page,`${width}-${theme}-${entry}-row-edit`);await dismissModal(page);}await click(page,del);await shot(page,`${width}-${theme}-${entry}-row-delete`);await click(page,'取消');await back(page);}
await click(page,'管理与配置');for(const [kind,path,title] of admin){await click(page,title);if(['users','menus','user-dict','dict-types','dict-data'].includes(kind)){await click(page,kind==='menus'?'编辑模拟菜单':'编辑');await shot(page,`${width}-${theme}-admin-${kind}-edit`);await dismissModal(page);if(kind==='menus')await click(page,'模拟菜单更多操作');await click(page,kind==='menus'?'删除菜单':'删除');await shot(page,`${width}-${theme}-admin-${kind}-delete`);await click(page,'取消');if(['menus','dict-data','dict-types'].includes(kind))await dismissModal(page);}else if(kind==='feedback'){await click(page,'详情');await shot(page,`${width}-${theme}-admin-feedback-detail`);await dismissModal(page);}else if(kind==='config'){await page.locator('[aria-label="配置值"] textarea').fill('{invalid');await click(page,'保存配置');await shot(page,`${width}-${theme}-admin-config-invalid`);}else await shot(page,`${width}-${theme}-admin-${kind}-row`);await back(page);}
});
for(const width of [390,768,1440])for(const theme of ['light','dark'])test(`补充选择器政策菜单锁海报和兼容编辑 ${width} ${theme}`,async({page})=>{
await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});await setup(page);await page.locator('uni-tabbar').getByText('我',{exact:true}).click();
await click(page,'账号绑定');await click(page,'新增绑定');await page.locator('uni-picker').click();await shot(page,`${width}-${theme}-bindings-platform-picker`);if(await page.locator('.uni-picker-action-confirm:visible').count())await page.locator('.uni-picker-action-confirm:visible').click();else await page.locator('.uni-picker-select .uni-picker-item').getByText('GitHub',{exact:true}).click();await shot(page,`${width}-${theme}-bindings-picker-confirm`);await click(page,'取消');await back(page);
await click(page,'菜单锁');for(const action of ['保存菜单锁','忘记密码']){await click(page,action);await shot(page,`${width}-${theme}-security-${action}`);await dismissModal(page);}await back(page);
await click(page,'CBTI 测试');await click(page,'开始测试');await click(page,'模拟选项');await click(page,'完成问卷');await shot(page,`${width}-${theme}-cbti-hidden`);await click(page,'茶');await expect(page.getByRole('button',{name:'生成海报',exact:true})).toBeVisible();await shot(page,`${width}-${theme}-cbti-result`);await click(page,'生成海报');await expect(page.getByRole('button',{name:'保存海报',exact:true})).toBeVisible();await shot(page,`${width}-${theme}-cbti-poster`);await back(page);
await click(page,'管理与配置');await click(page,'管理分类');await shot(page,`${width}-${theme}-category-admin`);await click(page,'编辑分类');await page.locator('[aria-label="选择图标"]').click();await shot(page,`${width}-${theme}-category-icon-picker`);if(await page.locator('.uni-picker-action-cancel:visible').count())await page.locator('.uni-picker-action-cancel:visible').click();else if(await page.locator('.uni-picker-select .uni-picker-item:visible').count())await page.locator('.uni-picker-select .uni-picker-item:visible').first().click();await dismissModal(page);await back(page);await back(page);
await click(page,'退出登录');await click(page,'退出');await click(page,'注册账号');for(const policy of ['隐私政策','服务条款']){await click(page,policy);await shot(page,`${width}-${theme}-auth-${policy}`);await dismissModal(page);}await back(page);
await page.locator('[aria-label="账号"] input').fill('fixture');await page.locator('[aria-label="密码"] input').fill('fixture-password');await click(page,'登录');await page.locator('.dashboard-scroll').waitFor();await page.goto('/#/pages/time/edit?id=9223372036854775807&date=2026-10-01');await page.getByRole('dialog').waitFor();await shot(page,`${width}-${theme}-time-edit-compat`);await click(page,'选择分类');await shot(page,`${width}-${theme}-time-category-select`);await page.getByRole('dialog',{name:'选择分类',exact:true}).getByRole('button',{name:'学习',exact:true}).click();await click(page,'删除记录');await shot(page,`${width}-${theme}-time-delete-confirm`);await page.getByRole('button',{name:'取消',exact:true}).first().click();await dismissModal(page);await expect(page.locator('.dashboard-scroll')).toBeVisible();
});
test('真实点击错误重试401403与生成API Key',async({page})=>{
await page.setViewportSize({width:390,height:900});const state=await setup(page,true);await page.locator('uni-tabbar').getByText('我',{exact:true}).click();
await click(page,'API Key');await click(page,'新增');await page.locator('[aria-label="备注"] input').fill('模拟生成Key');await click(page,'保存');await expect(page.getByRole('dialog',{name:'新 API Key',exact:true})).toBeVisible();await shot(page,'390-light-key-generated');await dismissModal(page);await back(page);
await click(page,'管理与配置');state.failPath='/api/user-center/list';await click(page,'用户中心');await expect(page.getByRole('alert')).toContainText('模拟加载失败');await shot(page,'390-light-admin-failed');state.failPath='';await click(page,'重试');await expect(page.getByText('fixture-row',{exact:true})).toBeVisible();state.failPath='/api/user-center/list';state.status=403;await click(page,'查询');await expect(page.getByRole('alert')).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('aio-life-mobile.access-token.v1'))).toBe('platform-fixture');await shot(page,'390-light-admin-403');state.status=401;await click(page,'查询');await expect(page).toHaveURL(/login\/index/);expect(await page.evaluate(()=>localStorage.getItem('aio-life-mobile.access-token.v1'))).toBeFalsy();await shot(page,'390-light-admin-401');
});
for(const width of [390,768,1440])for(const theme of ['light','dark'])test(`CBTI类型详情历史编辑删除逐层 ${width} ${theme}`,async({page})=>{
await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});const state=await setup(page,true);await page.locator('uni-tabbar').getByText('我',{exact:true}).click();await click(page,'CBTI 测试');await click(page,'QA · 模拟人格');await shot(page,`${width}-${theme}-cbti-type-detail`);await dismissModal(page);await click(page,'删除测试记录');await shot(page,`${width}-${theme}-cbti-history-delete`);await click(page,'取消');await click(page,'查看历史');await shot(page,`${width}-${theme}-cbti-history-result`);await click(page,'返回');await click(page,'人格管理');await click(page,'编辑人格');await shot(page,`${width}-${theme}-cbti-admin-edit`);state.fail=true;await click(page,'保存人格');await expect(page.getByRole('dialog').last().getByRole('alert')).toContainText('模拟保存失败');await shot(page,`${width}-${theme}-cbti-admin-fail`);state.fail=false;await dismissModal(page);await click(page,'删除人格');await shot(page,`${width}-${theme}-cbti-admin-delete`);await click(page,'取消');await dismissModal(page);
});
async function nativePicker(page, locator, name) {
  await locator.click();
  await shot(page, `390-light-deep-${name}-picker`);
  const nativeDate = locator.locator('input[type="date"]');
  const endPicker = page.getByRole('dialog', { name: '选择结束时间', exact: true });
  if (await nativeDate.count()) {
    await nativeDate.press('Escape');
    await nativeDate.press('Tab');
  } else if (await endPicker.count()) {
    await endPicker.getByRole('button', { name: '取消', exact: true }).click();
    await expect(endPicker).toHaveCount(0);
  } else {
    await page.locator('.uni-picker-action-cancel:visible').click();
  }
}
test('390补漏：阅读观影关联选择与运动细项',async({page})=>{
await page.setViewportSize({width:390,height:900});const errors=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);
await page.route('**/api/timeTrackerCategory/list',route=>route.fulfill({json:{rscode:'0',data:[{id:'1',name:'学习',color:'#427bea'},{id:'2',name:'运动',color:'#3fb27f'},{id:'3',name:'阅读',color:'#427bea'},{id:'4',name:'观影',color:'#427bea'}]}}));
await page.route('**/api/timeRecord/relateTypes',route=>route.fulfill({json:{rscode:'0',data:[{label:'阅读',value:1},{label:'观影',value:2}]}}));
await page.route('**/api/userDictType/getByDictType?*',route=>route.fulfill({json:{rscode:'0',data:{dictDetailList:[{id:'9223372036854775806',dictLabel:'跑步'},{id:'9223372036854775805',dictLabel:'俯卧撑'}]}}}));
await page.route(/\/api\/(read-record|movie)\/page\?/,route=>route.fulfill({json:{rscode:'0',data:{items:[{id:'9223372036854775807',title:'模拟关联记录'}],total:1}}}));
for(const category of ['阅读','观影','运动']){await click(page,'新增时迹');await click(page,'选择分类');await page.getByRole('dialog',{name:'选择分类',exact:true}).getByRole('button',{name:category,exact:true}).click();
if(category!=='运动'){await page.getByRole('button',{name:/选择关联阅读|选择关联观影/}).click();await expect(page.getByRole('dialog',{name:'选择关联记录',exact:true})).toBeVisible();await shot(page,`390-light-deep-time-${category}-related`);await dismissModal(page);await page.getByRole('button',{name:/选择关联阅读|选择关联观影/}).click();await page.getByRole('button',{name:/模拟关联记录/}).click();await shot(page,`390-light-deep-time-${category}-selected`);await click(page,'清除关联记录');}
else{await page.getByRole('button',{name:/添加运动/}).click();await page.locator('[aria-label="运动数量"] input').fill('12');await click(page,'运动项目 1');await expect(page.getByRole('dialog',{name:'选择运动',exact:true})).toBeVisible();await shot(page,'390-light-deep-exercise-type');await dismissModal(page);await shot(page,'390-light-deep-time-exercise-row');await click(page,'移除运动 1');}
await dismissModal(page);await expect(page.locator('.dashboard-scroll')).toBeVisible();}
await page.waitForTimeout(400);expect(errors).toEqual([]);
});
test('390补漏：通知删除测试接收人与反馈状态回复控件',async({page})=>{
await page.setViewportSize({width:390,height:900});const errors=[];page.on('pageerror',e=>errors.push(e.message));const state=await setup(page,true);await page.route('**/api/notification/channels/feishu/recipients',route=>route.fulfill({json:{rscode:'0',data:{items:[{name:'模拟接收人',openId:'fixture-recipient'}]}}}));await page.locator('uni-tabbar').getByText('我',{exact:true}).click();await click(page,'通知设置');await click(page,'删除飞书配置');await shot(page,'390-light-deep-notification-delete');await click(page,'取消');await click(page,'测试通知');await expect(page.getByText('测试已发送',{exact:true})).toBeVisible();await shot(page,'390-light-deep-notification-test-toast');await click(page,'配置飞书');await click(page,'选择接收人');await expect(page.getByRole('button',{name:'模拟接收人',exact:true})).toBeVisible();await shot(page,'390-light-deep-notification-recipients');await click(page,'模拟接收人');await expect(page.locator('[aria-label="接收人 Open ID"] input')).toHaveValue('fixture-recipient');await dismissModal(page);await back(page);
await click(page,'管理与配置');await click(page,'反馈管理');await click(page,'详情');const detail=page.getByRole('dialog',{name:'反馈详情',exact:true});await nativePicker(page,detail.locator('[aria-label="状态"]'),'feedback-status');await detail.locator('[aria-label="回复"] textarea').fill('仅模拟回复');state.fail=true;await detail.getByRole('button',{name:'回复',exact:true}).click();await expect(detail.getByRole('alert')).toContainText('模拟保存失败');await shot(page,'390-light-deep-feedback-reply-fail');await expect(detail.locator('[aria-label="回复"] textarea')).toHaveValue('仅模拟回复');state.fail=false;await detail.getByRole('button',{name:'回复',exact:true}).click();await expect(detail.locator('[aria-label="回复"] textarea')).toHaveValue('');await shot(page,'390-light-deep-feedback-reply-success');await detail.getByRole('button',{name:'更新状态',exact:true}).click();await shot(page,'390-light-deep-feedback-status-update');await dismissModal(page);await page.waitForTimeout(400);expect(errors).toEqual([]);
});
test('390补漏：设置与管理深层picker逐个开关',async({page})=>{
await page.setViewportSize({width:390,height:900});const errors=[];page.on('pageerror',e=>errors.push(e.message));await setup(page,true);await page.locator('uni-tabbar').getByText('我',{exact:true}).click();
for(const [entry,action,label,key] of [['API Key','新增','有效期','key-expiry'],['系统设置',null,'主题','theme']]){await click(page,entry);if(action)await click(page,action);await nativePicker(page,page.locator(`[aria-label="${label}"]`),key);if(action)await dismissModal(page);await back(page);}
await click(page,'管理与配置');for(const [kind,title,fields] of [['users','用户中心',['角色']],['menus','菜单管理',['父菜单','启用状态']],['dict-data','字典数据',['字典类型']],['user-dict','用户字典管理',['字典类型','状态','只读']]]){await click(page,title);await click(page,kind==='menus'?'编辑模拟菜单':'编辑');for(const field of fields)await nativePicker(page,page.getByRole('dialog').locator(`[aria-label="${field}"]`),`admin-${kind}-${field}`);await dismissModal(page);await back(page);}
for(const [title,fields] of [['字典数据',['字典类型筛选','已加载数据排序']],['用户字典管理',['类型','状态']],['反馈管理',['类型','状态']]]){await click(page,title);for(const field of fields){if(title==='字典数据' && field==='已加载数据排序')await click(page,'排序设置');const fieldNode=page.locator(`[aria-label="${field}"]`);if(await fieldNode.count())await nativePicker(page,fieldNode,`${title}-${field}`);}await back(page);}
await page.waitForTimeout(400);expect(errors).toEqual([]);
});
test('390最终补齐：绑定说明与时迹周期视图日期时间picker',async({page})=>{
await page.setViewportSize({width:390,height:900});const errors=[];page.on('pageerror',e=>errors.push(e.message));await setup(page,true);await page.locator('uni-tabbar').getByText('我',{exact:true}).click();await click(page,'账号绑定');await click(page,'新增绑定');await click(page,'填写说明');await expect(page.locator('.binding-hint')).toBeVisible();await shot(page,'390-light-final-binding-help-open');await click(page,'填写说明');await expect(page.locator('.binding-hint')).toHaveCount(0);await shot(page,'390-light-final-binding-help-closed');await click(page,'取消');await back(page);
await page.locator('uni-tabbar').getByText('时迹',{exact:true}).click();for(const mode of ['日','周','月']){await click(page,mode+'视图');await expect(page.getByRole('button',{name:mode+'视图',exact:true})).toHaveAttribute('aria-pressed','true');await shot(page,'390-light-final-time-'+mode);}
await click(page,'卡片视图');await expect(page.getByRole('button',{name:'卡片视图',exact:true})).toHaveAttribute('aria-pressed','true');await shot(page,'390-light-final-time-card');await expect(page.locator('.time-statistics')).toBeVisible();await shot(page,'390-light-final-time-statistics');await click(page,'时间轴视图');await nativePicker(page,page.locator('.date-switch uni-picker'),'final-time-date');
await click(page,'新增时迹');await nativePicker(page,page.getByRole('dialog').locator('uni-picker[aria-label="记录日期"]'),'final-editor-date');for(const [index,name] of [[0,'start'],[1,'end']])await nativePicker(page,page.getByRole('dialog').locator('.compact-time-picker').nth(index),'final-editor-'+name);await dismissModal(page);await expect(page.getByRole('button',{name:'新增时迹',exact:true})).toBeVisible();await page.waitForTimeout(400);expect(errors).toEqual([]);
});
test('390新SVG代表性复核：首页返回编辑器删除关闭',async({page})=>{
await page.setViewportSize({width:390,height:900});await setup(page,true);const evidence=[];
async function centered(selector,name,content=false){await page.locator(selector).first().waitFor();const rows=await page.locator(selector).evaluateAll((nodes,useContent)=>nodes.map(n=>{const b=n.getBoundingClientRect();const c=n.querySelector(useContent?'.action-content':'.category-icon-image')?.getBoundingClientRect();return{selector:n.className,label:n.getAttribute('aria-label'),width:b.width,height:b.height,iconWidth:c?.width,iconHeight:c?.height,dx:c?c.x+c.width/2-b.x-b.width/2:null,dy:c?c.y+c.height/2-b.y-b.height/2:null};}),content);expect(rows.length).toBeGreaterThan(0);for(const r of rows){expect(r.dx).not.toBeNull();expect(Math.abs(r.dx)).toBeLessThanOrEqual(1);expect(Math.abs(r.dy)).toBeLessThanOrEqual(1);}evidence.push({name,rows});await shot(page,'390-light-svg-refresh-'+name);}
await centered('.dashboard-action','home-four-actions',true);expect(await page.locator('.dashboard-action').count()).toBe(4);await page.locator('uni-tabbar').getByText('我',{exact:true}).click();await click(page,'关于');await centered('.navigation-button','pageheader-return');await back(page);
await click(page,'修改密码');await click(page,'修改密码');await expect(page.locator('.modal-close')).toHaveCount(0);await shot(page,'390-light-editor-without-title-close');await dismissModal(page);await back(page);await page.locator('uni-tabbar').getByText('首页',{exact:true}).click();await page.goto('/#/pages/time/edit?id=9223372036854775807&date=2026-10-01');await page.getByRole('dialog').waitFor();await centered('.delete-button','editor-delete');await click(page,'删除记录');await shot(page,'390-light-svg-refresh-delete-confirm');await page.getByRole('button',{name:'取消',exact:true}).first().click();await dismissModal(page);
await page.route('**/api/timeTrackerCategory/list',route=>route.fulfill({json:{rscode:'0',data:[{id:'3',name:'阅读',color:'#427bea'}]}}));await page.route('**/api/timeRecord/relateTypes',route=>route.fulfill({json:{rscode:'0',data:[{label:'阅读',value:1}]}}));await click(page,'新增时迹');await click(page,'选择分类');await page.getByRole('dialog',{name:'选择分类',exact:true}).getByRole('button',{name:'阅读',exact:true}).click();await page.getByRole('button',{name:/选择关联阅读|选择关联观影/}).click();await expect(page.getByRole('dialog',{name:'选择关联记录',exact:true})).toBeVisible();await shot(page,'390-light-related-picker');await dismissModal(page);await dismissModal(page);
fs.writeFileSync('/tmp/qa-platform-evidence/390-light-svg-refresh-geometry.json',JSON.stringify(evidence,null,2));
});
