const {test,expect}=require('@playwright/test')
const {dashboardFixture}=require('./fixtures.js')
const id='9223372036854775807'
async function setup(page){const state={writes:[],fail:false,exercise:[{id,exerciseTypeId:'81',exerciseDate:'2026-10-01',exerciseCount:20,description:'模拟运动',timeId:'9223372036854775806'}],devices:[{id,name:'模拟设备',spec:'模拟配置',type:'81',status:'1',purchaseDate:'2026-09-01',purchasePrice:100,purchasePlace:'模拟商店',remark:'模拟说明'}],movies:[{id,title:'模拟电影',type:1,status:'in_progress',director:'模拟导演',currentProgress:1,totalProgress:3,remark:'模拟影评',doubanSubjectId:'123'}],activity:[{id,performanceName:'模拟活动',performer:'模拟参与人',venue:'模拟场地',performanceType:'1',performanceDate:'2026-10-01',ticketPrice:50,orderNumber:'模拟订单',files:[]}],video:[{id,title:'模拟视频',url:'https://www.bilibili.com/video/BV1234567890',duration:100,watchedDuration:20,episodes:2,currentEpisode:1,status:'in_progress',notes:'模拟笔记',pagesInfo:'[{"page":1,"duration":50},{"page":2,"duration":50}]',bvid:'BV1234567890',ownerName:'模拟UP'}],thoughts:[{id,content:'模拟闪念',isPinned:0,hiddenContent:false,events:[{id:'31',content:'模拟事件'}]}],memos:[{id,title:'模拟笔记',content:'模拟正文',hiddenContent:false}],anniversaries:[{id,title:'模拟纪念日',targetDate:'2026-10-01',note:'模拟备注',icon:'🎉',color:'from-pink-400 to-rose-500'}],milestones:[{id,title:'模拟里程碑',date:'2026-10-01',end_date:'2026-10-02',type:'life',tags:'["模拟标签"]'}],honors:[{id,title:'模拟荣誉',honorDate:'2026-10-01',issuer:'模拟机构',level:'other',category:'other',tags:'["模拟标签"]',isTop:0,files:[]}],members:[{id,name:'模拟会员',provider:'模拟平台',category:'video',startDate:'2026-10-01',expiryDate:'2026-11-01',price:20,monthlyAmount:20,billingCycle:'month',status:'active',remainingDays:31,autoRenew:1}]}
await page.route('http://127.0.0.1:5180/api/**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname,method=req.method();let data=dashboardFixture(path);if(path==='/api/auth/login')data={accessToken:'records-fixture'};if(path==='/api/user/info')data={id:'6',nickname:'模拟用户',accountUsername:'fixture'};
if(path==='/api/thought/query')data={items:state.thoughts,total:1};if(path==='/api/memo/query')data={items:state.memos,total:1};if(path==='/api/anniversaryRecords'&&method==='GET')data=state.anniversaries;if(path==='/api/milestones'&&method==='GET')data=state.milestones;if(path==='/api/honorRecords'&&method==='GET')data=state.honors;if(path==='/api/honorCategories')data=[];if(path==='/api/membership/list')data=state.members;if(path==='/api/membership/stats')data={activeCount:1,monthlyAmount:20};if(path.endsWith('/getByDictType'))data={dictDetailList:url.searchParams.get('dictType')==='device_status'?[{id:'82',value:'1',label:'使用中'}]:[{id:'81',value:'1',dictLabel:'模拟类型',label:'模拟类型'}]};if(path==='/api/exerciseRecord/query')data={items:state.exercise,total:1};if(path==='/api/device/query')data={items:state.devices,total:1};if(path==='/api/movie/page'||path==='/api/read-record/page')data={items:state.movies,total:1};if(path==='/api/movie/'+id||path==='/api/read-record/'+id)data=state.movies[0];if(path==='/api/performance'&&method==='GET')data={items:state.activity,total:1};if(path==='/api/b-video/query')data={items:state.video,total:1};if(path==='/api/b-video/getStatusCount')data={in_progress:1};if(path==='/api/b-video/statistics')data={studiedSeconds:20,totalSeconds:100,unstudiedSeconds:80};
if(path==='/api/weread/connection')data={connected:true};if(path==='/api/weread/sync')data={shelf:{books:[{bookId:'book-1',title:'模拟微信读书',author:'模拟作者',finishReading:0}]},notebooks:{books:[{bookId:'book-1',book:{title:'模拟微信读书'},noteCount:1}]},stats:{readDays:2,totalReadTime:3600,readTimes:{'1790784000':3600}},lastSyncTime:'模拟同步时间'};if(path==='/api/weread/progress')data={book:{progress:25,readingTime:3600}};if(path==='/api/weread/notes')data={marks:{chapters:[{chapterUid:1,title:'模拟第一章'}],updated:[{bookmarkId:'note-1',chapterUid:1,markText:'模拟划线',range:'1-2'}]},reviews:[{review:{reviewId:'review-1',chapterUid:1,range:'1-2',type:1,content:'模拟关联想法'}}]};
if(method!=='GET'&&path!=='/api/auth/login'&&path!=='/api/weread/sync'){const body=req.postData()?req.postDataJSON():null;state.writes.push({path,method,body});if(state.fail)return route.fulfill({json:{rscode:'1',result:'模拟保存失败'}});if(path==='/api/thought/'+id){Object.assign(state.thoughts[0],body);data=true}else if(path==='/api/memo/'+id){Object.assign(state.memos[0],body);data=true}else if(path==='/api/anniversaryRecords'){Object.assign(state.anniversaries[0],body);data=state.anniversaries[0]}else if(path==='/api/milestones'){Object.assign(state.milestones[0],body);data=state.milestones[0]}else if(path==='/api/honorRecords'){Object.assign(state.honors[0],body);data=state.honors[0]}else if(path==='/api/membership'){Object.assign(state.members[0],body);data=state.members[0]}else if(path==='/api/exerciseRecord/'+id){Object.assign(state.exercise[0],body);data=true}else if(path==='/api/device/'+id){Object.assign(state.devices[0],body);data=true}else if(path==='/api/movie'||path==='/api/read-record'){Object.assign(state.movies[0],body);data=null}else if(path==='/api/performance'){Object.assign(state.activity[0],body);data=state.activity[0]}else if(path==='/api/b-video/'+id){Object.assign(state.video[0],body);data=true}else data=true}
await route.fulfill({json:{rscode:'0',data:data===undefined?[]:data}})})
await page.goto('/');await page.locator('[aria-label="账号"] input').fill('fixture');await page.locator('[aria-label="密码"] input').fill('fixture-password');await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.locator('.dashboard-scroll')).toBeVisible();return state}
for(const width of [390,768,1440])for(const theme of ['light','dark'])test(`运动保存/关联/图表 ${width} ${theme}`,async({page})=>{await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});const state=await setup(page);await page.goto('/#/pages/records/exercise');await expect(page.getByText('模拟运动',{exact:true})).toBeVisible();await page.locator('[aria-label="编辑运动"]').click();await page.locator('[aria-label="运动数量"] input').fill('21');state.fail=true;await page.locator('[aria-label="保存"]').click();await expect(page.getByText('模拟保存失败',{exact:true})).toBeVisible();await expect(page.locator('[aria-label="运动数量"] input')).toHaveValue('21');state.fail=false;await page.locator('[aria-label="保存"]').click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(state.writes.at(-1).path).toBe('/api/exerciseRecord/'+id);expect(state.writes.at(-1).body).not.toHaveProperty('id');expect(state.writes.at(-1).body).not.toHaveProperty('timeId');expect(state.exercise[0].timeId).toBe('9223372036854775806');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)})
test('设备、电影、活动、视频编辑保留非表单关联字段',async({page})=>{const state=await setup(page);for(const [route,edit,label,value,path,extra,expected]of[['goods/devices','编辑设备','名称','模拟设备修改','/api/device/'+id,'spec','模拟配置'],['records/library?kind=movie','编辑记录','名称','模拟电影修改','/api/movie','doubanSubjectId','123'],['records/activity','编辑活动','活动名称','模拟活动修改','/api/performance','orderNumber','模拟订单'],['records/video','编辑视频','标题','模拟视频修改','/api/b-video/'+id,'pagesInfo','[{"page":1,"duration":50},{"page":2,"duration":50}]']]){await page.goto('/#/pages/'+route);await page.reload();if(route==='records/anniversary')await page.getByRole('button',{name:/更多操作：/}).first().click();await page.locator('[aria-label'+(['编辑视频','编辑活动','编辑荣誉','编辑订阅','编辑笔记','编辑里程碑'].includes(edit)?'^':'')+'="'+edit+(['编辑视频','编辑活动','编辑荣誉','编辑订阅','编辑笔记','编辑里程碑'].includes(edit)?'：':'')+'"]').click();await expect(page.getByRole('dialog')).toBeVisible();await page.locator('[aria-label="'+label+'"] input').fill(value);await page.locator('[aria-label="保存"]').click();await expect(page.getByRole('dialog')).toHaveCount(0);const write=state.writes.filter(w=>w.path===path).at(-1);if(path.endsWith('/'+id))expect(write.body).not.toHaveProperty('id');else expect(write.body.id).toBe(id);if(extra==='doubanSubjectId'){expect(write.body).not.toHaveProperty(extra);expect(state.movies[0][extra]).toBe(expected)}else expect(write.body[extra]).toBe(expected)}})
test('微信读书书架详情与划线关联想法',async({page})=>{await setup(page);await page.goto('/#/pages/records/weread');await expect(page.locator('.dashboard-metric').first()).toContainText('1小时');await page.getByRole('button',{name:'我的书架',exact:true}).click();await expect(page.getByText('模拟微信读书',{exact:true})).toBeVisible();await page.locator('[aria-label^="书籍详情："]').click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByText('25',{exact:true})).toBeVisible();await page.locator('[aria-label="查看笔记"]').click();await expect(page.getByText('模拟划线',{exact:true})).toBeVisible();await expect(page.getByText('模拟关联想法',{exact:true})).toBeVisible()})
test('闪念笔记纪念日里程碑荣誉会员编辑恢复及附属字段保留',async({page})=>{const state=await setup(page);for(const [route,edit,label,value,path,key,expected]of [['records/notes?kind=think','编辑闪念','内容','模拟闪念修改','/api/thought/'+id,'events',[{id:'31',content:'模拟事件'}]],['records/notes?kind=memo','编辑笔记','标题','模拟笔记修改','/api/memo/'+id,'hiddenContent',false],['records/anniversary','编辑纪念日','标题','模拟纪念日修改','/api/anniversaryRecords','note','模拟备注'],['records/milestones','编辑里程碑','标题','模拟里程碑修改','/api/milestones','end_date','2026-10-02'],['records/honor','编辑荣誉','标题','模拟荣誉修改','/api/honorRecords','issuer','模拟机构'],['member/index','编辑订阅','名称','模拟会员修改','/api/membership','autoRenew',1]]){await page.goto('/#/pages/'+route);await page.reload();if(route==='records/anniversary')await page.getByRole('button',{name:/更多操作：/}).first().click();await page.locator('[aria-label'+(['编辑视频','编辑活动','编辑荣誉','编辑订阅','编辑笔记','编辑里程碑'].includes(edit)?'^':'')+'="'+edit+(['编辑视频','编辑活动','编辑荣誉','编辑订阅','编辑笔记','编辑里程碑'].includes(edit)?'：':'')+'"]').click();await expect(page.getByRole('dialog')).toBeVisible();await page.locator('[aria-label="'+label+'"] input,[aria-label="'+label+'"] textarea').fill(value);state.fail=true;await page.locator('[aria-label="保存"]').click();await expect(page.getByText('模拟保存失败',{exact:true})).toBeVisible();state.fail=false;await page.locator('[aria-label="保存"]').click();await expect(page.getByRole('dialog')).toHaveCount(0);const write=state.writes.filter(w=>w.path===path).at(-1);if(path.endsWith('/'+id))expect(write.body).not.toHaveProperty('id');else expect(write.body.id).toBe(id);expect(write.body[key]).toEqual(expected)}})

test('微信读书下拉同步与失败重试保留数据', async ({ page }) => {
  const { pullDown } = require('./gestures');
  await setup(page);
  let calls = 0;
  let fail = false;
  await page.route('**/api/weread/sync?**', async route => {
    calls++;
    await route.fulfill({ json: fail
      ? { rscode: '1', result: '模拟同步失败' }
      : { rscode: '0', data: { stats: { totalReadTime: calls * 3600 }, lastSyncTime: '模拟同步时间' } }
    });
  });
  await page.goto('/#/pages/records/weread');
  const metric = page.locator('.dashboard-metric').first();
  await expect(metric).toContainText('1小时');
  await expect(page.getByRole('button', { name: '同步微信读书', exact: true })).toHaveCount(0);
  await expect(page.getByText('模拟同步时间', { exact: true })).toHaveCount(0);
  await pullDown(page, '.mobile-page-scroll');
  await expect(metric).toContainText('2小时');
  await expect(page.locator('.uni-scroll-view-refresher')).not.toBeVisible();
  fail = true;
  await pullDown(page, '.mobile-page-scroll');
  await expect(page.getByRole('alert')).toContainText('模拟同步失败');
  await expect(metric).toContainText('2小时');
  await expect(page.locator('.uni-scroll-view-refresher')).not.toBeVisible();
  fail = false;
  await page.getByRole('button', { name: '重试', exact: true }).click();
  await expect(metric).toContainText('4小时');
  await expect(page.getByRole('alert')).toHaveCount(0);
});
