const {test,expect}=require('@playwright/test');
const {start,close,picker,entries}=require('./qa-domains-ui');
const fs=require('node:fs');const dir='artifacts/spacing-audit/10';fs.mkdirSync(dir,{recursive:true});
const routes=['coding/github','coding/leetcode','coding/csdn','relationship/index','messages/index','mcp/index','vault/index'];
for(const route of routes)for(const [width,theme]of [[390,'light'],[390,'dark'],...(['messages/index','relationship/index','vault/index'].includes(route)?[[768,'light'],[1440,'dark']]:[])])test(`${route} ${width} ${theme}`,async({page})=>{
 test.setTimeout(90000);await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});const errors=[];page.on('pageerror',e=>errors.push(e.message));const state=await start(page,route,{existingVault:route==='vault/index'});
 state.messages=[...Array(3)].map((_,i)=>({id:String(99+i),senderId:'2',receiverId:'1',title:'模拟通知 '+i,content:'工作与日常安排的模拟消息内容，检查多行文本和操作栏间距。',isRead:false}));
 if(route==='coding/github'){await page.route('https://api.github.com/**',async r=>{const u=r.request().url();if(u.endsWith('/graphql'))return r.fulfill({json:{data:{user:{contributionsCollection:{contributionCalendar:{totalContributions:740,weeks:Array.from({length:52},(_,w)=>({contributionDays:Array.from({length:7},(_,d)=>({date:new Date(Date.UTC(2025,9,3+w*7+d)).toISOString().slice(0,10),contributionCount:(w+d)%5}))}))}}}}}});if(u.includes('/repos?'))return r.fulfill({json:[0,1,2].map(i=>({id:String(10+i),name:'life-fixture-'+i,full_name:'fixture/life-'+i,description:'模拟生活数据项目，覆盖多行仓库描述和统计信息。',language:'TypeScript',stargazers_count:16,forks_count:3,pushed_at:'2026-10-01',html_url:'https://example.test/repo',fork:false}))});return r.fallback()});await page.route('**/api/github/recent-commits**',r=>r.fulfill({json:{rscode:'0',data:[0,1,2].map(i=>({id:String(i),repo:'fixture/life',message:'模拟提交记录与多行说明 '+i,date:'2026-10-01',actor:'fixture'}))}}));await page.getByRole('button',{name:'返回',exact:true}).click();await page.getByRole('button',{name:entries.find(e=>e[0]===route)[2],exact:true}).click();await page.waitForLoadState('networkidle');}
 if(route==='coding/leetcode'){await page.route('**/leetcode-api/**',r=>r.fulfill({json:{data:{userProfilePublicProfile:{siteRanking:5},userProfileUserQuestionProgress:{numAcceptedQuestions:[{difficulty:'EASY',count:2}],numFailedQuestions:[],numUntouchedQuestions:[]},userContestRanking:{rating:1500},userCalendar:{submissionCalendar:'{}',streak:1,totalActiveDays:1},todayRecord:[0,1,2].map(i=>({date:'2026-10-01',userStatus:'AC',question:{translatedTitle:'模拟每日题目 '+i,titleSlug:'fixture'}})),recentACSubmissions:[0,1,2].map(i=>({submissionId:String(i),submitTime:'1790812800',question:{questionFrontendId:String(i),translatedTitle:'模拟近期通过题目 '+i,titleSlug:'fixture'}}))}}}));await page.getByRole('button',{name:'返回',exact:true}).click();await page.getByRole('button',{name:entries.find(e=>e[0]===route)[2],exact:true}).click();await page.waitForLoadState('networkidle');}
 const prefix=dir+'/'+route.replace('/','-')+'-'+width+'-'+theme,evidence=[],geometries=[];
 async function shot(label){await page.waitForTimeout(550);const path=prefix+'-'+label+'.png';await page.screenshot({path,fullPage:true});evidence.push(path);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);geometries.push({label,...await page.evaluate(()=>{const css=n=>({class:n.className,rect:n.getBoundingClientRect().toJSON(),padding:getComputedStyle(n).padding,gap:getComputedStyle(n).gap,marginBottom:getComputedStyle(n).marginBottom});return {toolbarButtons:[...document.querySelectorAll('.ui-toolbar [role=button]')].map(css),roots:[...document.querySelectorAll('.ui-page-body,.ui-page-inset')].map(css),cards:[...document.querySelectorAll('.ui-card')].map(css),rows:[...document.querySelectorAll('.ui-row,.ui-toolbar')].map(css)}})});}
 async function modal(action){await page.getByRole('button',{name:action,exact:true}).first().click();const dialog=page.locator('[role=dialog]:visible').last();await expect(dialog).toBeVisible();await shot(action+'-top');await dialog.locator('.uni-scroll-view').evaluateAll(ns=>ns.forEach(n=>n.scrollTop=n.scrollHeight));await shot(action+'-bottom');await close(page);}
 await shot('page');
 if(route==='relationship/index'){await modal('新增人物');await page.getByRole('button',{name:'模拟人物',exact:true}).first().click();await shot('人物详情');await modal('编辑人物');await modal('新增关系');await modal('编辑关系');await close(page);}
 if(route==='messages/index'){for(const mode of ['消息','私聊','管理']){if(mode!=='消息')await picker(page,'频道',mode);await shot(mode);await modal(mode==='管理'?'发送通知':'发送消息');}await picker(page,'频道','AI');await page.getByRole('button',{name:'模拟会话',exact:true}).click();await expect(page.getByText('模拟AI内容',{exact:true})).toBeVisible();await shot('AI');await modal('修改标题');}
 if(route==='mcp/index')await modal('查看并调用');
 if(route==='vault/index'){await page.getByRole('button',{name:'解锁',exact:true}).click();await shot('unlock');const dialog=page.locator('[role=dialog]:visible');await dialog.locator('[aria-label="主密码"] input').fill('qa-master');await dialog.getByRole('button',{name:'解锁',exact:true}).click();await expect(page.getByText('fixture-user',{exact:true})).toBeVisible();await shot('unlocked');await modal('新增密码');await modal('编辑密码');}
 for(const g of geometries)for(const c of g.cards)expect(c.padding).toBe('12px');expect(errors).toEqual([]);expect(state.calls).toEqual([]);fs.writeFileSync(prefix+'.json',JSON.stringify({route,width,theme,evidence,geometries,errors,scope:'Mock API, real login and life menu navigation; no writes'},null,2));
});
