const {test,expect}=require('@playwright/test');
const {start,close}=require('./qa-domains-ui');
const fs=require('node:fs');const dir='artifacts/spacing-audit/09';fs.mkdirSync(dir,{recursive:true});
for(const route of ['index','income','expense','import','cards'])for(const [width,theme]of [[390,'light'],[390,'dark'],...(['expense','cards'].includes(route)?[[768,'light'],[1440,'dark']]:[])])test(`finance ${route} ${width} ${theme}`,async({page})=>{
 test.setTimeout(60000);await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});const errors=[];page.on('pageerror',e=>errors.push(e.message));const state=await start(page,'finance/'+route);
 state.cards=[...Array(3)].map((_,i)=>({...state.cards[0],id:String(88+i),alias:i?'家庭备用卡 '+i:'日常消费信用卡',remark:'日常消费与家庭账户管理',tags:[{id:'tag-big-9223372036854775807',name:'模拟标签'}]}));
 if(['income','expense'].includes(route))await page.route('**/api/'+route+'/query**',r=>r.fulfill({json:{rscode:'0',data:{items:[...Array(3)].map((_,i)=>({id:String(92250+i),amt:100+i*15,incTypeId:'81',expTypeId:'81',payTypeId:'82',incDate:'2026-10-01',expTime:'2026-10-01T12:00:00',remark:'模拟家庭日常收支记录 '+i,transactionAmt:99,transactionNo:'fixture-'+i})),total:3}}}));
 if(['cards','income','expense'].includes(route)){await page.getByRole('button',{name:'返回',exact:true}).click();await page.getByRole('button',{name:({cards:'银行卡',income:'收入',expense:'支出'})[route],exact:true}).last().click();await page.waitForLoadState('networkidle');}
 if(['income','expense'].includes(route)){await page.locator('[role=button][aria-label="筛选"]').click();await page.waitForTimeout(300);}const prefix=`${dir}/${route}-${width}-${theme}`,evidence=[];
 async function shot(label){const file=prefix+'-'+label+'.png';await page.screenshot({path:file,fullPage:true});evidence.push(file);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 async function modal(action){await page.getByRole('button',{name:action==='编辑银行卡'?/^编辑银行卡：/:action,exact:true}).first().click();const dialog=page.locator('[role=dialog]').last();await expect(dialog).toBeVisible();await shot(action+'-top');await dialog.locator('.uni-scroll-view').evaluateAll(ns=>ns.forEach(n=>n.scrollTop=n.scrollHeight));await shot(action+'-bottom');await close(page);await page.waitForTimeout(180);}
 if(route==='import'){await page.getByRole('button',{name:'粘贴 CSV 内容',exact:true}).click();await page.locator('[aria-label="支付宝 CSV 内容"] textarea').fill('交易号,商户订单号,交易创建时间,付款时间,最近修改时间,交易来源地,交易类型,交易对方,商品名称,金额（元）,收/支,交易状态,服务费（元）,成功退款（元）,备注,资金状态\nfixture1,fixtureM,2026-10-01 01:00:00,2026-10-01 01:00:00,,PC,餐饮,商店,商品,99,支出,交易成功,0,72.6,fixture,已支付');await page.locator('[role=button][aria-label="解析预览"]').click();await expect(page.getByText('1 笔 · ¥26.40',{exact:true})).toBeVisible();}
 await shot('page');const geometry=await page.evaluate(()=>{const css=n=>n?{rect:n.getBoundingClientRect().toJSON(),padding:getComputedStyle(n).padding,gap:getComputedStyle(n).gap,marginBottom:getComputedStyle(n).marginBottom}:null;const root=document.querySelector('.ui-page-body'),filter=document.querySelector('.ui-field-row');return{root:css(root),card:css(document.querySelector('.record.ui-card,.card.ui-card')),toolbar:css(document.querySelector('.ui-toolbar')),filter:css(filter),fields:filter?[...filter.children].slice(0,2).map(css):[],chart:[...document.querySelectorAll('.mini-chart')].map(css)}});
 expect(geometry.root.rect.x).toBe(width===1440?252:12);if(geometry.card)expect(geometry.card.padding).toBe('12px');if(geometry.toolbar)expect(geometry.toolbar.gap).toBe('8px');if(geometry.fields.length===2)expect(Math.abs(geometry.fields[0].rect.width-geometry.fields[1].rect.width)).toBeLessThan(1);
 if(['income','expense','cards'].includes(route)){await modal(route==='cards'?'新增银行卡':'新增');await modal(route==='cards'?'编辑银行卡':'编辑');if(route==='cards')await page.getByRole('button',{name:'银行卡更多操作'}).first().click();await page.getByRole(route==='cards'?'menuitem':'button',{name:route==='cards'?'删除银行卡':'删除',exact:true}).first().click();await shot('delete-confirm');await page.getByRole('button',{name:'取消',exact:true}).click();}
 if(route==='import')await modal('编辑');await page.locator('.mobile-page-scroll:visible .uni-scroll-view').last().evaluate(async n=>{n.scrollTop=0});const height=await page.locator('.mobile-page-content:visible').last().evaluate(n=>n.scrollHeight);for(let y=0;y<height;y+=800){await page.locator('.mobile-page-scroll:visible .uni-scroll-view').last().evaluate((n,y)=>n.scrollTop=y,y);await page.waitForTimeout(120);await shot('scroll-'+y)}expect(errors).toEqual([]);expect(state.calls).toEqual([]);fs.writeFileSync(prefix+'.json',JSON.stringify({route,width,theme,geometry,evidence,errors,scope:'H5 mocked login and life menu navigation; no writes'},null,2));
});
