const { dismissModal } = require('./modal');
const {test,expect}=require('@playwright/test');
const fs=require('node:fs'); const {setup,admin}=require('./qa-platform-fixtures');
const out='artifacts/spacing-audit/11';fs.mkdirSync(out,{recursive:true});
async function click(p,n){
 if (p.url().includes('/pages/profile/index') && ['账号绑定','修改密码','菜单锁'].includes(n)) {
  await p.getByRole('button',{name:'账号与安全',exact:true}).click();
 }
 await p.getByRole('button',{name:n,exact:true}).last().click();
}
async function back(p){
 const previous = p.url();
 await p.getByRole('button',{name:'返回',exact:true}).first().click();
 await expect(p).not.toHaveURL(previous);
 if (p.url().includes('/pages/profile/account-security')) {
  await p.getByRole('button',{name:'返回',exact:true}).first().click();
 }
}
async function shot(p,n){await p.waitForTimeout(180);if(process.env.SPACING11_REUSE_EVIDENCE!=='1'||!fs.existsSync(`${out}/${n}.png`)||fs.statSync(`${out}/${n}.png`).size===0)await p.screenshot({path:`${out}/${n}.png`,fullPage:true});const g=await p.locator('.mobile-page-content,.ui-page-body,.ui-card,.modal-content,.modal-panel,.ui-toolbar,.ui-field-row,.icon-button,.navigation-button,.ui-field-compact,.ui-row,.profile-entry').evaluateAll(ns=>ns.filter(n=>n.getBoundingClientRect().width).map(n=>{const b=n.getBoundingClientRect(),s=getComputedStyle(n);return{class:n.className,x:b.x,y:b.y,width:b.width,height:b.height,padding:s.padding,paddingTop:s.paddingTop,paddingRight:s.paddingRight,paddingBottom:s.paddingBottom,paddingLeft:s.paddingLeft,gap:s.gap,margin:s.margin,display:s.display}}));fs.writeFileSync(`${out}/${n}.json`,JSON.stringify(g,null,2));for(const row of g){if(row.class.includes('ui-card'))expect(row.padding).toBe('12px');if(row.class.includes('ui-modal-content')){const spacing=require('../../src/styles/spacing.json');expect(row.paddingTop).toBe(spacing.modalTop+'px');for(const side of ['paddingRight','paddingBottom','paddingLeft'])expect(row[side]).toBe(spacing.modal+'px');}if(row.class.includes('ui-field-compact'))expect(row.margin).toBe('0px');if(row.class.includes('navigation-button')||row.class.includes('icon-button')){expect(row.width).toBeGreaterThanOrEqual(44);expect(row.height).toBeGreaterThanOrEqual(44);}}expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
async function dialog(p,n,action){await click(p,action);const d=p.getByRole('dialog').last();await expect(d).toBeVisible();await shot(p,n);await d.evaluate(n=>{const all=[n,...n.querySelectorAll('*')];const scroll=all.filter(x=>x.scrollHeight>x.clientHeight+5 && /auto|scroll/.test(getComputedStyle(x).overflowY));scroll.forEach(x=>x.scrollTop=x.scrollHeight)});await shot(p,n+'-bottom');await dismissModal(p);}
test('11 手机平台全部物理页与模式',async({page:p})=>{test.setTimeout(180000);await p.setViewportSize({width:390,height:900});await setup(p,true);await p.route('**/api/menu/preferences',r=>r.fulfill({json:{rscode:'0',data:{menus:[{id:'category',title:'个人分类',children:[]},{id:'categoryadmin',title:'管理分类',children:[]},{id:'dashboard',title:'时间看板',children:[]}],hiddenMenuIds:[]}}}));await p.locator('uni-tabbar').getByText('我',{exact:true}).click();await shot(p,'390-light-profile');let i=0;
for(const [entry,key,action] of [['基本设置','settings',null],['账号绑定','bindings','新增绑定'],['修改密码','password','修改密码'],['菜单显示','menu',null],['菜单锁','security','修改二级密码'],['API Key','keys','新增'],['通知设置','notifications','配置飞书'],['系统设置','system',null],['MBTI 测试','mbti','历史详情'],['CBTI 测试','cbti','QA · 模拟人格'],['关于','about',null]]){const theme=i++%2?'dark':'light';await p.emulateMedia({colorScheme:theme});await click(p,entry);await shot(p,`390-${theme}-${key}`);if(action)await dialog(p,`390-${theme}-${key}-modal`,action);if(key==='mbti'){await click(p,'开始测试');await expect(p).toHaveURL(/personality\/external/);await shot(p,'390-light-external');await back(p);}await back(p);}
await click(p,'管理与配置');await shot(p,'390-light-admin-directory');for(const [kind,path,title] of admin){await p.emulateMedia({colorScheme:i++%2?'dark':'light'});await click(p,title);await shot(p,`390-admin-${kind}`);if(['users','menus','user-dict','dict-types','dict-data'].includes(kind)){await dialog(p,`390-admin-${kind}-new`,'新增');await dialog(p,`390-admin-${kind}-edit`,kind==='menus'?'编辑模拟菜单':'编辑');}await back(p);}await click(p,'管理分类');await shot(p,'390-dark-categories-admin');await dialog(p,'390-dark-categories-admin-modal','编辑分类');await back(p);await back(p);
await p.locator('uni-tabbar').getByText('全部',{exact:true}).click();await click(p,'个人分类');await shot(p,'390-light-categories-personal');await dialog(p,'390-light-categories-modal','编辑分类');await back(p);await p.locator('uni-tabbar').getByText('我',{exact:true}).click();await click(p,'退出登录');await click(p,'退出');await shot(p,'390-dark-login');for(const entry of ['注册账号','忘记密码']){await click(p,entry);await shot(p,entry==='注册账号'?'390-light-auth-register':'390-dark-auth-reset');await back(p);}
});
for(const width of [768,1440])test(`11 平板桌面 ${width}`,async({page:p})=>{test.setTimeout(90000);await p.setViewportSize({width,height:900});await setup(p,true);await p.route('**/api/menu/preferences',r=>r.fulfill({json:{rscode:'0',data:{menus:[{id:'category',title:'个人分类',children:[]},{id:'categoryadmin',title:'管理分类',children:[]},{id:'dashboard',title:'时间看板',children:[]}],hiddenMenuIds:[]}}}));await p.locator('uni-tabbar').getByText('我',{exact:true}).click();await shot(p,`${width}-light-profile`);await click(p,'API Key');await shot(p,`${width}-light-preferences`);await dialog(p,`${width}-light-key-modal`,'新增');await back(p);await p.emulateMedia({colorScheme:'dark'});await click(p,'管理与配置');await click(p,'用户中心');await shot(p,`${width}-dark-admin`);await dialog(p,`${width}-dark-admin-modal`,'编辑');});
