const { dismissModal } = require('./modal');
const {test,expect}=require('@playwright/test');const fs=require('node:fs');const {setup}=require('./qa-platform-fixtures');const out='artifacts/spacing-audit/12';fs.mkdirSync(out,{recursive:true});
async function click(p,n){await p.getByRole('button',{name:n,exact:true}).last().click()}
async function shot(p,n){await p.waitForTimeout(200);await p.screenshot({path:`${out}/${n}.png`,fullPage:true});const g=await p.locator('.mobile-page-content,.dashboard-content,.overview-grid,.overview-cell,.overview-card,.section-grid,.section-cell,.dashboard-section,.section-body,.ui-card,.ui-page-body,.form-card,.modal-panel,.modal-content,.life-content').evaluateAll(ns=>ns.filter(n=>n.getBoundingClientRect().width).map(n=>{const b=n.getBoundingClientRect(),s=getComputedStyle(n);return{class:n.className,x:b.x,y:b.y,width:b.width,height:b.height,padding:s.padding,margin:s.margin,gap:s.gap}}));fs.writeFileSync(`${out}/${n}.json`,JSON.stringify(g,null,2));expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
async function modal(p,n){await p.getByRole('dialog').last().evaluate(n=>[n,...n.querySelectorAll('*')].filter(x=>x.scrollHeight>x.clientHeight+5&&/auto|scroll/.test(getComputedStyle(x).overflowY)).forEach(x=>x.scrollTop=0));await shot(p,n+'-top');await p.getByRole('dialog').last().evaluate(n=>[n,...n.querySelectorAll('*')].filter(x=>x.scrollHeight>x.clientHeight+5&&/auto|scroll/.test(getComputedStyle(x).overflowY)).forEach(x=>x.scrollTop=x.scrollHeight));await shot(p,n+'-bottom');await dismissModal(p)}
for(const width of [390,768,1440])for(const theme of ['light','dark'])test(`12 final ${width} ${theme}`,async({page:p})=>{test.setTimeout(90000);await p.setViewportSize({width,height:900});await p.emulateMedia({colorScheme:theme});await setup(p,true);await p.route('**/api/menu/preferences?client=mobile',r=>r.fulfill({json:{code:0,data:{menus:[{id:'category',title:'个人分类'},{id:'categoryadmin',title:'管理分类'},{id:'dashboard',title:'时间看板'}],hiddenMenuIds:[]}}}));await shot(p,`${width}-${theme}-home`);await click(p,'新增时迹');await modal(p,`${width}-${theme}-home-editor`);await p.locator('uni-tabbar').getByText('时迹',{exact:true}).click();await shot(p,`${width}-${theme}-time`);await click(p,'新增时迹');await modal(p,`${width}-${theme}-time-editor`);await p.locator('uni-tabbar').getByText('全部',{exact:true}).click();await shot(p,`${width}-${theme}-life`);await p.locator('uni-tabbar').getByText('首页',{exact:true}).click();await click(p,'管理快捷导航');await shot(p,`${width}-${theme}-life-edit`);await click(p,'取消编辑');await p.route('**/api/timeRecord/queryByDateRange?*',r=>r.fulfill({json:{code:0,data:[{id:'9223372036854775807',categoryId:'1',date:'2026-10-01',startTime:540,endTime:599,title:'模拟学习记录'},{id:'9223372036854775806',categoryId:'2',date:'2026-10-01',startTime:660,endTime:689,title:'模拟运动记录'}]}}));await p.route('**/api/timeTrackerCategory/all',r=>r.fulfill({json:{code:0,data:[{id:'1',name:'学习',color:'#427bea'},{id:'2',name:'运动',color:'#3fb27f'}]}}));await click(p,'时间看板');await shot(p,`${width}-${theme}-dashboard`);await click(p,'返回');if(width!==1440){await p.goto('/#/pages/time/edit?id=9223372036854775807&date=2026-10-01');await p.getByRole('dialog').waitFor();await modal(p,`${width}-${theme}-compat-editor`)} });
test('12 associated selection',async({page:p})=>{await p.setViewportSize({width:390,height:900});await setup(p,true);await p.route('**/api/timeTrackerCategory/list',r=>r.fulfill({json:{code:0,data:[{id:'3',name:'阅读',color:'#427bea'}]}}));await p.route('**/api/timeRecord/relateTypes',r=>r.fulfill({json:{code:0,data:[{label:'阅读',value:1}]}}));await p.route(/\/api\/read-record\/page\?/,r=>r.fulfill({json:{code:0,data:{items:[{id:'9223372036854775807',title:'模拟阅读关联记录（完整标题检查）'}],total:1}}}));await click(p,'新增时迹');await click(p,'选择分类');await click(p,'阅读');await p.getByRole('button',{name:/选择关联阅读|选择关联观影/}).click();await shot(p,'390-light-related');await dismissModal(p);await dismissModal(p)});

test('12 long exercise editor',async({page:p})=>{await p.setViewportSize({width:390,height:900});await setup(p,true);await p.route('**/api/timeTrackerCategory/list',r=>r.fulfill({json:{code:0,data:[{id:'2',name:'运动',color:'#3fb27f'}]}}));await click(p,'新增时迹');await click(p,'选择分类');await click(p,'运动');for(let i=0;i<8;i++)await p.getByRole('button',{name:/添加运动/}).click();await modal(p,'390-light-long-editor')});
