const { dismissModal } = require('./modal');
const {test,expect}=require('@playwright/test');
const {setup,id}=require('./qa-records-fixtures.js');
const fs=require('fs');
const evidenceDir='artifacts/web-parity-tasks-records';
const cover='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="240" height="320"><rect width="240" height="320" fill="#6488b2"/><rect x="16" y="16" width="208" height="288" fill="#f2efe5"/><text x="120" y="160" text-anchor="middle" font-size="24" fill="#345">MOCK</text></svg>');
for(const width of [390,768,1440])for(const theme of ['light','dark'])test(`实页对照后的移动截图 ${width} ${theme}`,async({page})=>{
 test.setTimeout(120000);await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});const state=await setup(page);fs.mkdirSync(evidenceDir,{recursive:true});
 await page.route('**/mock-book.svg',r=>r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="240" height="320"><rect width="240" height="320" fill="#789abc"/><text x="120" y="160" text-anchor="middle" font-size="24">MOCK</text></svg>'}));
 const goals=Array.from({length:5},(_,i)=>({id:String(i+1),title:i===1?'模拟目标长标题，需要两行展示并保持信息层级一致':'模拟目标 '+(i+1),type:i+3,status:i===2?'completed':'in_progress',currentValue:2+i,targetValue:10,description:i===1?'模拟描述：记录每一天的变化。':'',tags:'["阅读"]',startDate:'2026-10-01 00:00:00',endDate:'2026-12-31 23:59:59'}));
 await page.route('**/api/goals*',r=>r.fulfill({json:{code:0,data:goals}}));
 await page.route('**/api/b-video/query*',r=>r.fulfill({json:{code:0,data:{items:Array.from({length:4},(_,i)=>({...state.video[0],id:String(i+1),cover,title:i===0?'模拟视频长标题，学习记录卡片应保留两行文字与视频进度':'模拟视频 '+i})),total:4}}}));
 await page.route('**/api/thought/query*',r=>r.fulfill({json:{code:0,data:{items:Array.from({length:4},(_,i)=>({...state.thoughts[0],id:String(i+1),content:i===0?'模拟闪念：正文应该是卡片的首要信息，日期在底部；关联事件在弹窗中按需查看。':'模拟闪念 '+i,createTime:'2026-10-01 10:00:00'})),total:4}}}));
 await page.route('**/api/weread/sync*',r=>r.fulfill({json:{code:0,data:{shelf:{books:Array.from({length:5},(_,i)=>({bookId:'book-'+i,title:'模拟图书 '+i,author:'模拟作者',cover:'http://127.0.0.1:5180/mock-book.svg',finishReading:i===1?1:0}))},notebooks:{books:[{bookId:'book-0',book:{title:'模拟图书 0'},noteCount:1}]},stats:{readDays:2,totalReadTime:3600,readTimes:{'1790784000':3600}},lastSyncTime:'模拟同步时间'}}}));
 await page.route('**/api/timeTrackerCategory/list',r=>r.fulfill({json:{code:0,data:Array.from({length:4},(_,i)=>({id:String(i+1),name:'模拟分类 '+i,color:'#5b8ff9',icon:'lucide:book',parentId:'0',timeType:i%3+1,isTrackTime:1,isEnabled:1,userId:'6'}))}}));
 await page.route('**/api/timeTrackerCategory/hidden',r=>r.fulfill({json:{code:0,data:[]}}));
 const cases=[['goals','tasks/goals',/^编辑目标：/],['todo','tasks/todo',/^任务详情：/],['think','records/notes?kind=think',/^编辑闪念$/],['memo','records/notes?kind=memo',/^编辑笔记：/],['video','records/video',/^编辑视频：/],['exercise','records/exercise',/^编辑运动$/],['categories','categories/index',/^编辑分类$/]];
 for(const [key,route,openName] of cases){await page.goto('/#/pages/'+route);await page.reload();const button=page.getByRole('button',{name:openName}).first();await expect(button).toBeVisible();if(key==='goals'){const cards=page.getByRole('button',{name:/^编辑目标：/});await expect(cards).toHaveCount(5);const first=await cards.nth(0).boundingBox(),second=await cards.nth(1).boundingBox();expect(Math.abs(first.y-second.y)).toBeLessThan(2);expect(first.width).toBeLessThan(width/2);expect(second.x).toBeGreaterThan(first.x+first.width);const title=cards.nth(1).locator('.record-title');const titleBox=await title.boundingBox();expect(titleBox.height).toBeLessThanOrEqual(52);}await page.screenshot({path:`${evidenceDir}/${key}-${width}-${theme}-page.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await button.click();await expect(page.getByRole('dialog')).toBeVisible();await page.screenshot({path:`${evidenceDir}/${key}-${width}-${theme}-modal.png`});const lastAction=page.getByRole('dialog').getByRole('button').last();await lastAction.scrollIntoViewIfNeeded();const actionBox=await lastAction.boundingBox();expect(actionBox.y+actionBox.height).toBeLessThanOrEqual(900);await page.screenshot({path:`${evidenceDir}/${key}-${width}-${theme}-modal-footer.png`});await dismissModal(page);await expect(page.getByRole('dialog')).toHaveCount(0);}
 await page.goto('/#/pages/records/weread');await page.reload();await expect(page.getByRole('button',{name:'我的书架',exact:true})).toBeVisible();await page.screenshot({path:`${evidenceDir}/weread-${width}-${theme}-dashboard.png`});await page.getByRole('button',{name:'我的书架',exact:true}).click();await expect(page.getByRole('button',{name:'书籍详情：模拟图书 0'})).toBeVisible();await page.screenshot({path:`${evidenceDir}/weread-${width}-${theme}-shelf.png`});await page.getByRole('button',{name:'书籍详情：模拟图书 0'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.screenshot({path:`${evidenceDir}/weread-${width}-${theme}-detail.png`});
});
