import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { transform } from 'esbuild'
import * as XLSX from 'xlsx'
globalThis.fixtureXLSX=XLSX
const source=await readFile(new URL('../src/services/domains/import-parser.ts',import.meta.url),'utf8')
const {code}=await transform(source.replace("import * as XLSX from 'xlsx';",'const XLSX=globalThis.fixtureXLSX'),{loader:'ts',format:'esm'})
const parser=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'))
const ctx={dictOptions:[{id:'9223372036854775807',label:'餐饮'}],payTypeOptions:[{id:'99',dictValue:'1',label:'支付宝'},{id:'88',dictValue:'2',label:'微信'}],defaultExpTypeId:'9223372036854775807'}
test('支付宝电脑端部分退款保留交易金额、分精度记账及大ID',()=>{const csv='交易号,商户订单号,交易创建时间,付款时间,最近修改时间,交易来源地,交易类型,交易对方,商品名称,金额（元）,收/支,交易状态,服务费（元）,成功退款（元）,备注,资金状态\nfixture1,fixtureM,2026-10-01 01:00:00,2026-10-01 01:00:00,,PC,餐饮,商店,商品,99,支出,交易成功,0,72.6,fixture,已支付';const result=parser.parseCSV(csv,ctx);assert.equal(result.transactions[0].amt,26.4);assert.equal(result.transactions[0].transactionAmt,99);assert.equal(result.transactions[0].expTypeId,ctx.defaultExpTypeId);assert.equal(result.transactions[0].payTypeId,'99')})
test('支付宝手机端排除收入，带引号商品字段完整',()=>{const csv='交易时间,交易分类,交易对方,对方账号,商品说明,收/支,金额,收/付款方式,交易状态,交易订单号,商家订单号,备注\n2026-10-01 00:00:00,餐饮,商店,fixture,"商品,餐点",支出,12.3,余额,交易成功,fixture2,fixture3,\n2026-10-01 00:00:00,餐饮,商店,fixture,其他,收入,99,余额,交易成功,fixture4,fixture5,';const result=parser.parseMobileCSV(csv,ctx);assert.equal(result.transactions.length,1);assert.equal(result.transactions[0].expDesc,'商品,餐点');assert.equal(result.transactions[0].amt,12.3)})
test('微信xlsx解析器存在且仅本地模拟文件',()=>{assert.equal(typeof parser.parseWechatExcel,'function');assert.equal(parser.excelDateToString('2026-10-01 01:02:03'),'2026-10-01 01:02:03')})
test('真实本地模拟xlsx行保留大交易号并扣减部分退款',()=>{const workbook=XLSX.utils.book_new();const sheet=XLSX.utils.aoa_to_sheet([['微信账单模拟'],['交易时间','交易类型','交易对方','商品','收/支','金额','支付方式','当前状态','交易单号','商户单号','备注'],['2026-10-01 01:02:03','餐饮','模拟商店','模拟商品','支出','￥99.00','零钱','已退款(￥72.60)','9223372036854775807','fixture-merchant','fixture'],['2026-10-01 01:02:03','餐饮','模拟商店','模拟商品','支出','￥99.00','零钱','已全额退款','fixture-refund','fixture-merchant','fixture']]);XLSX.utils.book_append_sheet(workbook,sheet,'模拟账单');const result=parser.parseWechatExcel(XLSX.write(workbook,{type:'array',bookType:'xlsx'}),ctx);assert.equal(result.transactions.length,1);assert.equal(result.transactions[0].transactionId,'9223372036854775807');assert.equal(result.transactions[0].amt,26.4);assert.equal(result.transactions[0].payTypeId,'88')});
test('原生GBK账单复用xlsx既有codepage能力',async()=>{const codepage=await import('xlsx/dist/cpexcel.full.mjs');const bytes=new Uint8Array(codepage.utils.encode(936,'模拟账单'));const source=await readFile(new URL('../src/services/domains/import-files.ts',import.meta.url),'utf8');const end=source.indexOf('export async function parseBillFile');let only=source.slice(0,end).replace(/^import .*$/gm,'').replace(/\/\/ #ifdef WEB[\s\S]*?\/\/ #endif/,'');only=only.replace("'xlsx/dist/cpexcel.full.mjs'",JSON.stringify(new URL('../node_modules/xlsx/dist/cpexcel.full.mjs',import.meta.url).href));const {code}=await transform(only,{loader:'ts',format:'esm'});const files=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));assert.equal(await files.decodeBill(bytes.buffer),'模拟账单');assert.equal(await files.decodeBill(new TextEncoder().encode('UTF-8模拟').buffer),'UTF-8模拟')});
