import { withFormRequired } from './helpers/form-required-source.mjs';
import {readFile} from 'node:fs/promises'
import assert from 'node:assert/strict'
import test from 'node:test'
const asModule=value=>`data:text/javascript;base64,${Buffer.from(withFormRequired(value)).toString('base64')}`
const source=await readFile(new URL('../src/services/personality/contract.ts',import.meta.url),'utf8')
const {entityId,safeExternalUrl,mbtiPayload,cbtiPayload,vectorValue,personalityPayload,authPayload,shareText}=await import(asModule(source))
const id='9223372036854775807'
test('历史ID不转number，外部地址只允许https',()=>{assert.equal(entityId(id),id);assert.throws(()=>entityId(1),/ID/);assert.throws(()=>safeExternalUrl('javascript:alert(1)'),/无效/);assert.equal(safeExternalUrl('https://devil.ai/test/abc'),'https://devil.ai/test/abc')})
test('MBTI 保存完整预测/特质/匹配与结果页，恢复JSON历史',()=>{assert.deepEqual(mbtiPayload('fixture',{mbtiType:'INTP',predictions:'{"Ti":80}',traitOrderConscious:{hero:'Ti'},traitOrderShadow:{critic:'Te'},matches:'["ENTP"]',resultsPage:'https://example.test/result'}),{testId:'fixture',mbtiType:'INTP',predictions:{Ti:80},traitOrderConscious:{hero:'Ti'},traitOrderShadow:{critic:'Te'},matches:['ENTP'],resultsPage:'https://example.test/result'});assert.throws(()=>mbtiPayload('fixture',{}),/未完成/)})
test('CBTI逐题校验，非coffee不传陈旧态度，coffee需要第二隐藏题',()=>{const questions=[{id:1,options:[{value:0},{value:2}]},{id:2,options:[{value:1}]}];assert.throws(()=>cbtiPayload(questions,{1:0},{drink:'tea'}),/第2题/);assert.deepEqual(cbtiPayload(questions,{1:0,2:1,99:9},{drink:'tea',drinkAttitude:'stale'}),{answers:{1:0,2:1},hiddenAnswers:{drink:'tea'}});assert.throws(()=>cbtiPayload(questions,{1:0,2:1},{drink:'coffee'}),/咖啡/);assert.equal(cbtiPayload(questions,{1:0,2:1},{drink:'coffee',drinkAttitude:'need'}).hiddenAnswers.drinkAttitude,'need')})
test('15维向量只允许数字0/1/2，管理员字段完整且过滤元数据',()=>{const vector=Array(15).fill(1);assert.deepEqual(vectorValue(JSON.stringify(vector)),vector);assert.throws(()=>vectorValue(Array(15).fill('1')),/15项/);assert.throws(()=>vectorValue(Array(14).fill(1)),/15项/);const payload=personalityPayload({id,code:' CODE ',name:'演示',vector,strengths:'一\n 二 ',weaknesses:'三',imageObject:'cbti/test.png',isSpecial:true,userId:'99'});assert.deepEqual(payload.strengths,['一','二']);assert.deepEqual(payload.weaknesses,['三']);assert.equal(payload.imageObject,'cbti/test.png');assert.equal('userId' in payload,false);assert.equal('id' in payload,false)})
test('注册和重置严格密码确认，提交不包含确认/客户端字段',()=>{const form={username:'demo',email:'demo@example.test',password:'fixture-secret',confirmPassword:'fixture-secret',code:'123456',remember:true};assert.deepEqual(authPayload('register',form),{username:'demo',email:'demo@example.test',password:'fixture-secret',code:'123456'});assert.equal('username' in authPayload('reset',form),false);assert.throws(()=>authPayload('reset',{...form,confirmPassword:'different'}),/不一致/);assert.throws(()=>authPayload('register',{...form,email:'broken'}),/邮箱/)})
test('分享文案保留人格和匹配度',()=>{assert.match(shareText({personality:{code:'CODE',name:'演示',motto:'格言'},similarity:90},'https://example.test'),/CODE · 演示.*\n「格言」\n匹配度 90%\nhttps:\/\/example.test/)})
