import {readFile} from 'node:fs/promises'
import assert from 'node:assert/strict'
import test from 'node:test'
import {transform} from 'esbuild'
import * as XLSX from 'xlsx'
const sourceImport=source=>import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'))
async function service(name){let source=await readFile(new URL('../src/services/records/'+name+'.ts',import.meta.url),'utf8');source=source.replace(/import \{ request \} from ['"]\.\.\/api\.ts['"]/, 'const request = globalThis.__mediaRequest').replace(/import \{ recordId \} from ['"]\.\/contracts\.ts['"]/, 'const recordId = value => { if(typeof value !== "string") throw Error("ID"); return value }');return sourceImport((await transform(source,{loader:'ts',format:'esm'})).code)}
test('运动/分类/设备/活动实际契约保持字符串关联且不用1000条截断统计接口',async()=>{const calls=[];globalThis.__mediaRequest=async(...args)=>{calls.push(args);return true};const exercise=await service('exercise'),goods=await service('goods');await exercise.fetchExercisePage(2,'9223372036854775807');await exercise.saveExercise({id:'9223372036854775807',timeId:'9223372036854775806'});await exercise.deleteExercises(['9223372036854775807']);await exercise.saveCategory({id:'81',dictType:'exercise_type',dictSort:10});await goods.savePerformance({id:'89',fileIds:[]});assert.deepEqual(calls[0],['/exerciseRecord/query','GET',{page:2,pageSize:100,exerciseTypeId:'9223372036854775807'}]);assert.equal(calls[1][0],'/exerciseRecord/9223372036854775807');assert.equal(calls[1][2].timeId,'9223372036854775806');assert.deepEqual(calls[2][2],{idList:['9223372036854775807']});assert.equal(calls[3][0],'/userDictData');assert.deepEqual(calls[4],['/performance','PUT',{id:'89',fileIds:[]}]);assert(!calls.some(call=>call[0].includes('statistics')));delete globalThis.__mediaRequest})
test('微信读书同步POST查询参数及长超时，笔记/进度实际GET契约',async()=>{const calls=[];globalThis.__mediaRequest=async(...args)=>calls.push(args);const api=await service('weread');await api.syncWeread('monthly',1790784000);await api.fetchWereadNotes('book-1');await api.fetchWereadProgress('book-1');assert.equal(calls[0][0],'/weread/sync?mode=monthly&baseTime=1790784000');assert.equal(calls[0][1],'POST');assert.equal(calls[0][6],120000);assert.deepEqual(calls[1].slice(0,3),['/weread/notes','GET',{bookId:'book-1'}]);assert.deepEqual(calls[2].slice(0,3),['/weread/progress','GET',{bookId:'book-1'}]);delete globalThis.__mediaRequest})
test('视频BV/av解析保留标识及分P信息服务字段',async()=>{globalThis.__mediaRequest=async()=>true;const api=await service('video');assert.deepEqual(api.extractVideoId('https://www.bilibili.com/video/BV1234567890?p=2'),{bvid:'BV1234567890'});assert.deepEqual(api.extractVideoId('av1234'),{aid:'1234'});assert.throws(()=>api.extractVideoId('https://example.com'),/BV/);delete globalThis.__mediaRequest})
test('豆瓣工作簿导入严格表头、长ID、Excel日期、重复及错误行',async()=>{globalThis.__mediaXlsx=XLSX.default||XLSX;const source=(await readFile(new URL('../src/services/records/douban-import.ts',import.meta.url),'utf8')).replace("import * as XLSX from 'xlsx';",'const XLSX=globalThis.__mediaXlsx;');const api=await sourceImport((await transform(source,{loader:'ts',format:'esm'})).code);const workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet([['format','aio-life-douban-movies'],['version','1'],['source','douban'],['douban_user_id','fixture-user']]),'_Meta');const headers=['douban_subject_id','title','type','director','url','status','marked_date','rating','remark'];XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet([headers,['9223372036854775807','模拟影片','movie','模拟导演','https://movie.douban.com/subject/9223372036854775807/','completed',46326,5,'模拟评价'],['22','错误评分','movie','','https://movie.douban.com/subject/22/','completed','2026-10-01',6,'']]),'Movies');const parsed=api.parseDoubanWorkbook(XLSX.write(workbook,{type:'array',bookType:'xlsx'}));assert.equal(parsed.total,2);assert.equal(parsed.request.records.length,1,JSON.stringify(parsed.issues));assert.equal(parsed.request.records[0].doubanSubjectId,'9223372036854775807');assert.match(parsed.request.records[0].markedDate,/^\d{4}-\d{2}-\d{2}$/);assert.equal(parsed.issues.length,1);assert.match(parsed.issues[0].message,/rating/);delete globalThis.__mediaXlsx})
