import {createRequire} from 'node:module'
import {mkdir} from 'node:fs/promises'
import assert from 'node:assert/strict'
const {chromium}=createRequire(import.meta.url)('@playwright/test'),browser=await chromium.launch({channel:'chrome',headless:true}),output=new URL('../test-results/wardrobe/',import.meta.url).pathname
await mkdir(output,{recursive:true});const id='9223372036854775807',categoryId='9223372036854775806'
try{for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:1000}])for(const theme of ['light','dark']){
const context=await browser.newContext({viewport});await context.addInitScript(theme=>{localStorage.setItem('aio-life-mobile.access-token.v1','synthetic-token');localStorage.setItem('aio-life-mobile.theme.v1',theme)},theme);const page=await context.newPage(),state={fail:false,writes:[],row:{id,name:'冬衣',categoryId,categoryName:'个人分类',color:'白',brand:'测试品牌',season:'秋,冬',purchaseDate:'2026-01-01',price:99.5,fileId:'999',size:'M',memo:'保留备注'}};
await page.route('http://127.0.0.1:5180/api/**',async route=>{const request=route.request(),path=new URL(request.url()).pathname,method=request.method();let data=[];if(path==='/api/file/preview/999')return route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jG2kAAAAASUVORK5CYII=','base64')});if(path==='/api/user/info')data={id:'7',username:'fixture',roles:['admin']};if(path==='/api/wardrobe/items')data=state.row?[state.row]:[];if(path==='/api/wardrobe/items/'+id&&method==='GET')data=state.row;if(path==='/api/wardrobe/categories')data=[{id:'1',name:'系统分类',categoryType:0},{id:categoryId,name:'个人分类',categoryType:1,sort:0}];if(path==='/api/wardrobe/stats')data={totalCount:1,totalValue:99.5,avgPrice:99.5,seasonCount:{秋:1,冬:1},categoryCount:{个人分类:1}};if(path==='/api/wardrobe/items/'+id&&method==='PUT'){const body=request.postDataJSON();state.writes.push(body);if(state.fail)return route.fulfill({json:{code:1,message:'模拟衣物保存失败'}});state.row={...state.row,...body,season:body.season.join(',')};data=true}if(path==='/api/wardrobe/items/'+id&&method==='DELETE'){state.row=null;data=true}return route.fulfill({json:{code:0,data}})});
await page.goto('http://127.0.0.1:5180/#/pages/goods/wardrobe');await page.locator('img').first().waitFor();await page.waitForFunction(()=>Array.from(document.querySelectorAll('img')).some(image=>image.src.startsWith('blob:')&&image.complete&&image.naturalWidth>0));await page.getByRole('button',{name:'编辑衣物冬衣',exact:true}).click();const dialog=page.getByRole('dialog',{name:'衣物编辑'});await dialog.getByRole('textbox',{name:'名称',exact:true}).fill('冬衣改名');state.fail=true;await dialog.getByRole('button',{name:'保存衣柜内容'}).click();await page.getByText('模拟衣物保存失败',{exact:true}).waitFor();assert.equal(await dialog.getByRole('textbox',{name:'名称',exact:true}).inputValue(),'冬衣改名');assert.equal(state.writes.at(-1).categoryId,categoryId);assert.equal(state.writes.at(-1).fileId,'999');assert.equal(state.writes.at(-1).memo,'保留备注');assert.deepEqual(state.writes.at(-1).season,['秋','冬']);await page.screenshot({path:output+viewport.width+'-'+theme+'.png',fullPage:true});state.fail=false;await dialog.getByRole('button',{name:'保存衣柜内容'}).click();await page.getByText('冬衣改名',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.getByRole('button',{name:'分类',exact:true}).click();await page.getByText('系统分类',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'编辑分类系统分类'}).count(),0);await context.close();console.log('衣柜 '+viewport.width+' '+theme+' 失败保留/完整字段/长ID/预设保护通过')}
}finally{await browser.close()}
