import SecureRandom from 'java.security.SecureRandom'
import { SecureRandomHex } from '../interface.uts'

export const secureRandomHex: SecureRandomHex = (length: number): string => {
  if (length < 1 || length > 4096 || Math.floor(length) != length) return ''
  const random = new SecureRandom()
  const alphabet = '0123456789abcdef'
  let result = ''
  for (let i = 0; i < length * 2; i++) result += alphabet.charAt(random.nextInt(16))
  return result
}
